openapi: 3.0.1
info:
  description: Specification for ManagedServices.
  title: ManagedServicesClient
  version: 2019-09-01
  x-apisguru-categories:
  - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
  - format: swagger
    url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/managedservices/resource-manager/Microsoft.ManagedServices/stable/2019-09-01/managedservices.json
    version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: managedservices
  x-tags:
  - Azure
  - Microsoft
servers:
- url: https://management.azure.com/
security:
- azure_auth:
  - user_impersonation
paths:
  /providers/Microsoft.ManagedServices/operations:
    get:
      description: Gets a list of the operations.
      operationId: Operations_List
      parameters:
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationList'
          description: OK - Returns a list of operations.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - Operations
      x-ms-examples:
        Get Registration Operations:
          parameters:
            api-version: 2019-09-01
          responses:
            "200":
              body:
                value:
                - display:
                    description: Retrieves a list of Managed Services registration
                      definitions.
                    operation: List Managed Services Registration Definitions
                    provider: Microsoft Managed Services
                    resource: Managed Services Registration Definition
                  name: Microsoft.ManagedServices/registrationDefinitions/read
      x-accepts:
      - application/json
  /{scope}/providers/Microsoft.ManagedServices/marketplaceRegistrationDefinitions:
    get:
      description: Gets a list of the marketplace registration definitions for the
        marketplace identifier.
      operationId: MarketplaceRegistrationDefinitions_List
      parameters:
      - description: Scope of the resource.
        in: path
        name: scope
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
          x-ms-skip-url-encoding: true
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      - description: "The filter query parameter. Might be used to filter marketplace\
          \ registration definition by plan identifier, publisher, version etc."
        in: query
        name: $filter
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketplaceRegistrationDefinitionList'
          description: OK - Returns a list of the marketplace registration definitions.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - MarketplaceRegistrationDefinitions
      x-ms-examples:
        Get Registration Definitions:
          parameters:
            $filter: planIdentifier eq 'publisher.offerIdentifier.planName.version'
            api-version: 2019-09-01
            scope: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
          responses:
            "200":
              body:
                value:
                - id: /subscriptions/0afefe50-734e-4610-8a82-a144ahf49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-6e081c90ada2
                  name: 26c128c2-fefa-4340-9bb1-6e081c90ada2
                  plan:
                    name: addesai-plan
                    product: test
                    publisher: marketplace-test
                    version: 1.0.0
                  properties:
                    authorizations:
                    - principalId: f98g86a2-4cc4-4e6d-ad47-b3e80a1bcdfc
                      roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
                    description: Test
                    managedByTenantId: 83ace5cd-bcc3-441a-hd86-e6a75360cecc
                    managedByTenantName: Test Tenant
                    provisioningState: Succeeded
                    registrationDefinitionName: DefinitionName
                  type: Microsoft.ManagedServices/registrationDefinitions
      x-ms-pageable:
        nextLinkName: nextLink
      x-accepts:
      - application/json
  /{scope}/providers/Microsoft.ManagedServices/marketplaceRegistrationDefinitions/{marketplaceIdentifier}:
    get:
      description: Get the marketplace registration definition for the marketplace
        identifier.
      operationId: MarketplaceRegistrationDefinitions_Get
      parameters:
      - description: Scope of the resource.
        in: path
        name: scope
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
          x-ms-skip-url-encoding: true
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      - description: "Market place identifer. Expected Formats - {publisher}.{product[-preview]}.{planName}.{version}\
          \ or {publisher}.{product[-preview]}.{planName} or {publisher}.{product[-preview]}\
          \ or {publisher})."
        in: path
        name: marketplaceIdentifier
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationDefinition'
          description: OK - Returns the details of the marketplace registration definition.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - MarketplaceRegistrationDefinitions
      x-ms-examples:
        Get Registration Definitions:
          parameters:
            api-version: 2019-09-01
            marketplaceIdentifier: publisher.product.planName.version
            scope: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
          responses:
            "200":
              body:
                id: /subscriptions/0afefe50-734e-4610-8a82-a144ahf49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-6e081c90ada2
                name: 26c128c2-fefa-4340-9bb1-6e081c90ada2
                plan:
                  name: addesai-plan
                  product: test
                  publisher: marketplace-test
                  version: 1.0.0
                properties:
                  authorizations:
                  - principalId: f98g86a2-4cc4-4e6d-ad47-b3e80a1bcdfc
                    roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
                  description: Test
                  managedByTenantId: 83ace5cd-bcc3-441a-hd86-e6a75360cecc
                  managedByTenantName: Test Tenant
                  provisioningState: Succeeded
                  registrationDefinitionName: DefinitionName
                type: Microsoft.ManagedServices/registrationDefinitions
      x-accepts:
      - application/json
  /{scope}/providers/Microsoft.ManagedServices/registrationAssignments:
    get:
      description: Gets a list of the registration assignments.
      operationId: RegistrationAssignments_List
      parameters:
      - description: Scope of the resource.
        in: path
        name: scope
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
          x-ms-skip-url-encoding: true
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      - description: Tells whether to return registration definition details also
          along with registration assignment details.
        in: query
        name: $expandRegistrationDefinition
        schema:
          type: boolean
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationAssignmentList'
          description: OK - Returns a list of the registration assignments.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - RegistrationAssignments
      x-ms-examples:
        Get Registration Assignments:
          parameters:
            api-version: 2019-09-01
            scope: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
          responses:
            "200":
              body:
                value:
                - id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationAssignments/484a7d5f-9729-4b87-bc9b-26610985a013
                  name: 484a7d5f-9729-4b87-bc9b-26610985a013
                  properties:
                    provisioningState: Succeeded
                    registrationDefinition:
                      id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
                      name: 26c128c2-fefa-4340-9bb1-8e081c90ada2
                      plan:
                        name: addesai-plan
                        product: test
                        publisher: marketplace-test
                        version: 1.0.0
                      properties:
                        authorizations:
                        - principalId: f98d86a2-4cc4-4e9d-ad47-b3e80a1bcdfc
                          roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
                        description: Test
                        managedByTenantId: 83abe5cd-bcc3-441a-bd86-e6a75360cecc
                        managedByTenantName: Contoso Corp.
                        manageeTenantId: 01c0bcd5-4f47-4e4b-b492-418b7e2a8854
                        manageeTenantName: test_test_aad_SbtFhyGiLHPFm
                        provisioningState: Succeeded
                        registrationDefinitionName: DefinitionName
                      type: Microsoft.ManagedServices/registrationDefinitions
                    registrationDefinitionId: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
                  type: Microsoft.ManagedServices/registrationAssignments
      x-ms-pageable:
        nextLinkName: nextLink
      x-accepts:
      - application/json
  /{scope}/providers/Microsoft.ManagedServices/registrationAssignments/{registrationAssignmentId}:
    delete:
      description: Deletes the specified registration assignment.
      operationId: RegistrationAssignments_Delete
      parameters:
      - description: Scope of the resource.
        in: path
        name: scope
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
          x-ms-skip-url-encoding: true
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      - description: Guid of the registration assignment.
        in: path
        name: registrationAssignmentId
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: OK - The registration assignment is deleted.
        "202":
          content: {}
          description: Accepted - The registration assignment deletion operation is
            accepted.
        "204":
          content: {}
          description: No Content- The registration assignment does not exist.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - RegistrationAssignments
      x-ms-examples:
        Delete Registration Assignment:
          parameters:
            api-version: 2019-09-01
            registrationAssignmentId: 26c128c2-fefa-4340-9bb1-6e081c90ada2
            scope: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
          responses:
            "200": {}
            "202": {}
            "204": {}
      x-ms-long-running-operation: true
      x-accepts:
      - application/json
    get:
      description: Gets the details of specified registration assignment.
      operationId: RegistrationAssignments_Get
      parameters:
      - description: Scope of the resource.
        in: path
        name: scope
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
          x-ms-skip-url-encoding: true
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      - description: Guid of the registration assignment.
        in: path
        name: registrationAssignmentId
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Tells whether to return registration definition details also
          along with registration assignment details.
        in: query
        name: $expandRegistrationDefinition
        schema:
          type: boolean
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationAssignment'
          description: OK - Returns the registration assignment.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - RegistrationAssignments
      x-ms-examples:
        Get Registration Assignment:
          parameters:
            api-version: 2019-09-01
            registrationAssignmentId: 26c128c2-fefa-4340-9bb1-6e081c90ada2
            scope: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
          responses:
            "200":
              body:
                id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationAssignments/484a7d5f-9729-4b87-bc9b-26610985a013
                name: 484a7d5f-9729-4b87-bc9b-26610985a013
                properties:
                  provisioningState: Succeeded
                  registrationDefinition:
                    id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
                    name: 26c128c2-fefa-4340-9bb1-8e081c90ada2
                    plan:
                      name: addesai-plan
                      product: test
                      publisher: marketplace-test
                      version: 1.0.0
                    properties:
                      authorizations:
                      - principalId: f98d86a2-4cc4-4e9d-ad47-b3e80a1bcdfc
                        roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
                      description: Test
                      managedByTenantId: 83abe5cd-bcc3-441a-bd86-e6a75360cecc
                      managedByTenantName: Contoso Corp.
                      manageeTenantId: 01c0bcd5-4f47-4e4b-b492-418b7e2a8854
                      manageeTenantName: test_test_aad_SbtFhyGiLHPFm
                      provisioningState: Succeeded
                      registrationDefinitionName: DefinitionName
                    type: Microsoft.ManagedServices/registrationDefinitions
                  registrationDefinitionId: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
                type: Microsoft.ManagedServices/registrationAssignments
              headers: {}
      x-accepts:
      - application/json
    put:
      description: Creates or updates a registration assignment.
      operationId: RegistrationAssignments_CreateOrUpdate
      parameters:
      - description: Scope of the resource.
        in: path
        name: scope
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
          x-ms-skip-url-encoding: true
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      - description: Guid of the registration assignment.
        in: path
        name: registrationAssignmentId
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationAssignment'
        description: The parameters required to create new registration assignment.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationAssignment'
          description: Ok - Returns information about the updated registration assignment.
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationAssignment'
          description: Created - Returns information about the created registration
            assignment.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - RegistrationAssignments
      x-ms-examples:
        Put Registration Assignment:
          parameters:
            api-version: 2019-09-01
            registrationAssignmentId: 26c128c2-fefa-4340-9bb1-6e081c90ada2
            requestBody:
              properties:
                registrationDefinitionId: /subscriptions/0afefe50-734e-4610-8a82-a144ahf49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-6e081c90ada2
            scope: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
          responses:
            "200":
              body:
                id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationAssignments/484a7d5f-9729-4b87-bc9b-26610985a013
                name: 484a7d5f-9729-4b87-bc9b-26610985a013
                properties:
                  provisioningState: Succeeded
                  registrationDefinitionId: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
                type: Microsoft.ManagedServices/registrationAssignments
            "201":
              body:
                id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationAssignments/484a7d5f-9729-4b87-bc9b-26610985a013
                name: 484a7d5f-9729-4b87-bc9b-26610985a013
                properties:
                  provisioningState: Succeeded
                  registrationDefinitionId: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
                type: Microsoft.ManagedServices/registrationAssignments
      x-ms-long-running-operation: true
      x-codegen-request-body-name: requestBody
      x-content-type: application/json
      x-accepts:
      - application/json
  /{scope}/providers/Microsoft.ManagedServices/registrationDefinitions:
    get:
      description: Gets a list of the registration definitions.
      operationId: RegistrationDefinitions_List
      parameters:
      - description: Scope of the resource.
        in: path
        name: scope
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
          x-ms-skip-url-encoding: true
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationDefinitionList'
          description: OK - Returns a list of the registration definitions.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - RegistrationDefinitions
      x-ms-examples:
        Get Registration Definitions:
          parameters:
            api-version: 2019-09-01
            scope: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
          responses:
            "200":
              body:
                value:
                - id: /subscriptions/0afefe50-734e-4610-8a82-a144ahf49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-6e081c90ada2
                  name: 26c128c2-fefa-4340-9bb1-6e081c90ada2
                  plan:
                    name: addesai-plan
                    product: test
                    publisher: marketplace-test
                    version: 1.0.0
                  properties:
                    authorizations:
                    - principalId: f98g86a2-4cc4-4e6d-ad47-b3e80a1bcdfc
                      roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
                    description: Test
                    managedByTenantId: 83ace5cd-bcc3-441a-hd86-e6a75360cecc
                    managedByTenantName: Test Tenant
                    provisioningState: Succeeded
                    registrationDefinitionName: DefinitionName
                  type: Microsoft.ManagedServices/registrationDefinitions
      x-ms-pageable:
        nextLinkName: nextLink
      x-accepts:
      - application/json
  /{scope}/providers/Microsoft.ManagedServices/registrationDefinitions/{registrationDefinitionId}:
    delete:
      description: Deletes the registration definition.
      operationId: RegistrationDefinitions_Delete
      parameters:
      - description: Guid of the registration definition.
        in: path
        name: registrationDefinitionId
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      - description: Scope of the resource.
        in: path
        name: scope
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
          x-ms-skip-url-encoding: true
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      responses:
        "200":
          content: {}
          description: OK - The registration definition is deleted.
        "204":
          content: {}
          description: No Content- The registration definition does not exist.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - RegistrationDefinitions
      x-ms-examples:
        Delete Registration Definition:
          parameters:
            api-version: 2019-09-01
            registrationDefinitionId: 26c128c2-fefa-4340-9bb1-6e081c90ada2
            scope: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
          responses:
            "200": {}
            "204": {}
      x-accepts:
      - application/json
    get:
      description: Gets the registration definition details.
      operationId: RegistrationDefinitions_Get
      parameters:
      - description: Scope of the resource.
        in: path
        name: scope
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
          x-ms-skip-url-encoding: true
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      - description: Guid of the registration definition.
        in: path
        name: registrationDefinitionId
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationDefinition'
          description: OK - Returns the complete registration definition with plan
            details.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - RegistrationDefinitions
      x-ms-examples:
        Get Registration Definition:
          parameters:
            api-version: 2019-09-01
            registrationDefinitionId: 26c128c2-fefa-4340-9bb1-6e081c90ada2
            scope: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
          responses:
            "200":
              body:
                id: /subscriptions/0afefe50-734e-4610-8a82-a144ahf49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-6e081c90ada2
                name: 26c128c2-fefa-4340-9bb1-6e081c90ada2
                plan:
                  name: addesai-plan
                  product: test
                  publisher: marketplace-test
                  version: 1.0.0
                properties:
                  authorizations:
                  - principalId: f98g86a2-4cc4-4e6d-ad47-b3e80a1bcdfc
                    roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
                  description: Test
                  managedByTenantId: 83ace5cd-bcc3-441a-hd86-e6a75360cecc
                  managedByTenantName: Test Tenant
                  provisioningState: Succeeded
                  registrationDefinitionName: DefinitionName
                type: Microsoft.ManagedServices/registrationDefinitions
      x-accepts:
      - application/json
    put:
      description: Creates or updates a registration definition.
      operationId: RegistrationDefinitions_CreateOrUpdate
      parameters:
      - description: Guid of the registration definition.
        in: path
        name: registrationDefinitionId
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: The API version to use for this operation.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      - description: Scope of the resource.
        in: path
        name: scope
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
          x-ms-skip-url-encoding: true
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationDefinition'
        description: The parameters required to create new registration definition.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationDefinition'
          description: Ok - Returns information about the updated registration definition.
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationDefinition'
          description: Created - Returns information about the created registration
            definition.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      tags:
      - RegistrationDefinitions
      x-ms-examples:
        Put Registration Definition:
          parameters:
            api-version: 2019-09-01
            registrationDefinitionId: 26c128c2-fefa-4340-9bb1-6e081c90ada2
            requestBody:
              plan:
                name: addesai-plan
                product: test
                publisher: marketplace-test
                version: 1.0.0
              properties:
                authorizations:
                - principalId: f98d86a2-4cc4-4e9d-ad47-b3e80a1bcdfc
                  roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
                description: Tes1t
                managedByTenantId: 83abe5cd-bcc3-441a-bd86-e6a75360cecc
                registrationDefinitionName: DefinitionName
            scope: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
          responses:
            "200":
              body:
                id: /subscriptions/0afefe50-734e-4610-8a82-a144ahf49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-6e081c90ada2
                name: 26c128c2-fefa-4340-9bb1-6e081c90ada2
                plan:
                  name: addesai-plan
                  product: test
                  publisher: marketplace-test
                  version: 1.0.0
                properties:
                  authorizations:
                  - principalId: f98g86a2-4cc4-4e6d-ad47-b3e80a1bcdfc
                    roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
                  description: Test
                  managedByTenantId: 83ace5cd-bcc3-441a-hd86-e6a75360cecc
                  managedByTenantName: Test Tenant
                  provisioningState: Succeeded
                  registrationDefinitionName: DefinitionName
                type: Microsoft.ManagedServices/registrationDefinitions
            "201":
              body:
                id: /subscriptions/0afefe50-734e-4610-8a82-a144ahf49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-6e081c90ada2
                name: 26c128c2-fefa-4340-9bb1-6e081c90ada2
                plan:
                  name: addesai-plan
                  product: test
                  publisher: marketplace-test
                  version: 1.0.0
                properties:
                  authorizations:
                  - principalId: f98g86a2-4cc4-4e6d-ad47-b3e80a1bcdfc
                    roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
                  description: Test
                  managedByTenantId: 83ace5cd-bcc3-441a-hd86-e6a75360cecc
                  managedByTenantName: Test Tenant
                  provisioningState: Succeeded
                  registrationDefinitionName: DefinitionName
                type: Microsoft.ManagedServices/registrationDefinitions
      x-ms-long-running-operation: true
      x-codegen-request-body-name: requestBody
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  parameters:
    ApiVersionParameter:
      description: The API version to use for this operation.
      in: query
      name: api-version
      required: true
      schema:
        type: string
    ExpandRegistrationDefinition:
      description: Tells whether to return registration definition details also along
        with registration assignment details.
      in: query
      name: $expandRegistrationDefinition
      schema:
        type: boolean
        x-ms-parameter-location: method
      x-ms-parameter-location: method
    Filter:
      description: "The filter query parameter. Might be used to filter marketplace\
        \ registration definition by plan identifier, publisher, version etc."
      in: query
      name: $filter
      schema:
        type: string
        x-ms-parameter-location: method
      x-ms-parameter-location: method
    MarketplaceIdentifier:
      description: "Market place identifer. Expected Formats - {publisher}.{product[-preview]}.{planName}.{version}\
        \ or {publisher}.{product[-preview]}.{planName} or {publisher}.{product[-preview]}\
        \ or {publisher})."
      in: path
      name: marketplaceIdentifier
      required: true
      schema:
        type: string
        x-ms-parameter-location: method
      x-ms-parameter-location: method
    RegistrationAssignmentIdParameter:
      description: Guid of the registration assignment.
      in: path
      name: registrationAssignmentId
      required: true
      schema:
        type: string
        x-ms-parameter-location: method
      x-ms-parameter-location: method
    ScopeParameter:
      description: Scope of the resource.
      in: path
      name: scope
      required: true
      schema:
        type: string
        x-ms-parameter-location: method
        x-ms-skip-url-encoding: true
      x-ms-parameter-location: method
      x-ms-skip-url-encoding: true
    registrationDefinitionIdParameter:
      description: Guid of the registration definition.
      in: path
      name: registrationDefinitionId
      required: true
      schema:
        type: string
        x-ms-parameter-location: method
      x-ms-parameter-location: method
  schemas:
    Authorization:
      description: Authorization tuple containing principal Id (of user/service principal/security
        group) and role definition id.
      example:
        roleDefinitionId: roleDefinitionId
        principalId: principalId
      properties:
        principalId:
          description: Principal Id of the security group/service principal/user that
            would be assigned permissions to the projected subscription
          type: string
        roleDefinitionId:
          description: The role definition identifier. This role will define all the
            permissions that the security group/service principal/user must have on
            the projected subscription. This role cannot be an owner role.
          type: string
      required:
      - principalId
      - roleDefinitionId
      type: object
    ErrorResponse:
      description: Error response.
      example:
        error:
          code: code
          message: message
      properties:
        error:
          $ref: '#/components/schemas/ErrorResponse_error'
      type: object
    MarketplaceRegistrationDefinitionList:
      description: List of marketplace registration definitions.
      example:
        value:
        - name: name
          id: id
          type: type
          plan:
            product: product
            name: name
            publisher: publisher
            version: version
          properties:
            registrationDefinitionName: registrationDefinitionName
            managedByTenantId: managedByTenantId
            authorizations:
            - roleDefinitionId: roleDefinitionId
              principalId: principalId
            - roleDefinitionId: roleDefinitionId
              principalId: principalId
            description: description
            provisioningState: NotSpecified
            managedByTenantName: managedByTenantName
        - name: name
          id: id
          type: type
          plan:
            product: product
            name: name
            publisher: publisher
            version: version
          properties:
            registrationDefinitionName: registrationDefinitionName
            managedByTenantId: managedByTenantId
            authorizations:
            - roleDefinitionId: roleDefinitionId
              principalId: principalId
            - roleDefinitionId: roleDefinitionId
              principalId: principalId
            description: description
            provisioningState: NotSpecified
            managedByTenantName: managedByTenantName
        nextLink: nextLink
      properties:
        nextLink:
          description: Link to next page of marketplace registration definitions.
          readOnly: true
          type: string
        value:
          description: List of marketplace registration definitions.
          items:
            $ref: '#/components/schemas/RegistrationDefinition'
          readOnly: true
          type: array
      type: object
    Operation:
      description: Object that describes a single Microsoft.ManagedServices operation.
      example:
        display:
          provider: provider
          resource: resource
          description: description
          operation: operation
        name: name
      properties:
        display:
          $ref: '#/components/schemas/Operation_display'
        name:
          description: "Operation name: {provider}/{resource}/{operation}"
          readOnly: true
          type: string
      type: object
    OperationList:
      description: List of the operations.
      example:
        value:
        - display:
            provider: provider
            resource: resource
            description: description
            operation: operation
          name: name
        - display:
            provider: provider
            resource: resource
            description: description
            operation: operation
          name: name
      properties:
        value:
          description: List of Microsoft.ManagedServices operations.
          items:
            $ref: '#/components/schemas/Operation'
          readOnly: true
          type: array
      type: object
    Plan:
      description: Plan details for the managed services.
      example:
        product: product
        name: name
        publisher: publisher
        version: version
      properties:
        name:
          description: The plan name.
          type: string
        product:
          description: The product code.
          type: string
        publisher:
          description: The publisher ID.
          type: string
        version:
          description: The plan's version.
          type: string
      required:
      - name
      - product
      - publisher
      - version
      type: object
    RegistrationAssignment:
      description: Registration assignment.
      example:
        name: name
        id: id
        type: type
        properties:
          registrationDefinitionId: registrationDefinitionId
          provisioningState: NotSpecified
          registrationDefinition:
            name: name
            id: id
            type: type
            plan:
              product: product
              name: name
              publisher: publisher
              version: version
            properties:
              manageeTenantName: manageeTenantName
              manageeTenantId: manageeTenantId
              registrationDefinitionName: registrationDefinitionName
              managedByTenantId: managedByTenantId
              authorizations:
              - roleDefinitionId: roleDefinitionId
                principalId: principalId
              - roleDefinitionId: roleDefinitionId
                principalId: principalId
              description: description
              provisioningState: NotSpecified
              managedByTenantName: managedByTenantName
      properties:
        id:
          description: The fully qualified path of the registration assignment.
          readOnly: true
          type: string
        name:
          description: Name of the registration assignment.
          readOnly: true
          type: string
        properties:
          $ref: '#/components/schemas/RegistrationAssignmentProperties'
        type:
          description: Type of the resource.
          readOnly: true
          type: string
      type: object
      x-ms-azure-resource: true
    RegistrationAssignmentList:
      description: List of registration assignments.
      example:
        value:
        - name: name
          id: id
          type: type
          properties:
            registrationDefinitionId: registrationDefinitionId
            provisioningState: NotSpecified
            registrationDefinition:
              name: name
              id: id
              type: type
              plan:
                product: product
                name: name
                publisher: publisher
                version: version
              properties:
                manageeTenantName: manageeTenantName
                manageeTenantId: manageeTenantId
                registrationDefinitionName: registrationDefinitionName
                managedByTenantId: managedByTenantId
                authorizations:
                - roleDefinitionId: roleDefinitionId
                  principalId: principalId
                - roleDefinitionId: roleDefinitionId
                  principalId: principalId
                description: description
                provisioningState: NotSpecified
                managedByTenantName: managedByTenantName
        - name: name
          id: id
          type: type
          properties:
            registrationDefinitionId: registrationDefinitionId
            provisioningState: NotSpecified
            registrationDefinition:
              name: name
              id: id
              type: type
              plan:
                product: product
                name: name
                publisher: publisher
                version: version
              properties:
                manageeTenantName: manageeTenantName
                manageeTenantId: manageeTenantId
                registrationDefinitionName: registrationDefinitionName
                managedByTenantId: managedByTenantId
                authorizations:
                - roleDefinitionId: roleDefinitionId
                  principalId: principalId
                - roleDefinitionId: roleDefinitionId
                  principalId: principalId
                description: description
                provisioningState: NotSpecified
                managedByTenantName: managedByTenantName
        nextLink: nextLink
      properties:
        nextLink:
          description: Link to next page of registration assignments.
          readOnly: true
          type: string
        value:
          description: List of registration assignments.
          items:
            $ref: '#/components/schemas/RegistrationAssignment'
          readOnly: true
          type: array
      type: object
    RegistrationAssignmentProperties:
      description: Properties of a registration assignment.
      example:
        registrationDefinitionId: registrationDefinitionId
        provisioningState: NotSpecified
        registrationDefinition:
          name: name
          id: id
          type: type
          plan:
            product: product
            name: name
            publisher: publisher
            version: version
          properties:
            manageeTenantName: manageeTenantName
            manageeTenantId: manageeTenantId
            registrationDefinitionName: registrationDefinitionName
            managedByTenantId: managedByTenantId
            authorizations:
            - roleDefinitionId: roleDefinitionId
              principalId: principalId
            - roleDefinitionId: roleDefinitionId
              principalId: principalId
            description: description
            provisioningState: NotSpecified
            managedByTenantName: managedByTenantName
      properties:
        provisioningState:
          description: Current state of the registration assignment.
          enum:
          - NotSpecified
          - Accepted
          - Running
          - Ready
          - Creating
          - Created
          - Deleting
          - Deleted
          - Canceled
          - Failed
          - Succeeded
          - Updating
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: ProvisioningState
        registrationDefinition:
          $ref: '#/components/schemas/RegistrationAssignmentProperties_registrationDefinition'
        registrationDefinitionId:
          description: Fully qualified path of the registration definition.
          type: string
      required:
      - registrationDefinitionId
      type: object
    RegistrationDefinition:
      description: Registration definition.
      example:
        name: name
        id: id
        type: type
        plan:
          product: product
          name: name
          publisher: publisher
          version: version
        properties:
          registrationDefinitionName: registrationDefinitionName
          managedByTenantId: managedByTenantId
          authorizations:
          - roleDefinitionId: roleDefinitionId
            principalId: principalId
          - roleDefinitionId: roleDefinitionId
            principalId: principalId
          description: description
          provisioningState: NotSpecified
          managedByTenantName: managedByTenantName
      properties:
        id:
          description: Fully qualified path of the registration definition.
          readOnly: true
          type: string
        name:
          description: Name of the registration definition.
          readOnly: true
          type: string
        plan:
          $ref: '#/components/schemas/Plan'
        properties:
          $ref: '#/components/schemas/RegistrationDefinitionProperties'
        type:
          description: Type of the resource.
          readOnly: true
          type: string
      type: object
      x-ms-azure-resource: true
    RegistrationDefinitionList:
      description: List of registration definitions.
      example:
        value:
        - name: name
          id: id
          type: type
          plan:
            product: product
            name: name
            publisher: publisher
            version: version
          properties:
            registrationDefinitionName: registrationDefinitionName
            managedByTenantId: managedByTenantId
            authorizations:
            - roleDefinitionId: roleDefinitionId
              principalId: principalId
            - roleDefinitionId: roleDefinitionId
              principalId: principalId
            description: description
            provisioningState: NotSpecified
            managedByTenantName: managedByTenantName
        - name: name
          id: id
          type: type
          plan:
            product: product
            name: name
            publisher: publisher
            version: version
          properties:
            registrationDefinitionName: registrationDefinitionName
            managedByTenantId: managedByTenantId
            authorizations:
            - roleDefinitionId: roleDefinitionId
              principalId: principalId
            - roleDefinitionId: roleDefinitionId
              principalId: principalId
            description: description
            provisioningState: NotSpecified
            managedByTenantName: managedByTenantName
        nextLink: nextLink
      properties:
        nextLink:
          description: Link to next page of registration definitions.
          readOnly: true
          type: string
        value:
          description: List of registration definitions.
          items:
            $ref: '#/components/schemas/RegistrationDefinition'
          readOnly: true
          type: array
      type: object
    RegistrationDefinitionProperties:
      description: Properties of a registration definition.
      example:
        registrationDefinitionName: registrationDefinitionName
        managedByTenantId: managedByTenantId
        authorizations:
        - roleDefinitionId: roleDefinitionId
          principalId: principalId
        - roleDefinitionId: roleDefinitionId
          principalId: principalId
        description: description
        provisioningState: NotSpecified
        managedByTenantName: managedByTenantName
      properties:
        authorizations:
          description: Authorization tuple containing principal id of the user/security
            group or service principal and id of the build-in role.
          items:
            $ref: '#/components/schemas/Authorization'
          type: array
        description:
          description: Description of the registration definition.
          type: string
        managedByTenantId:
          description: Id of the managedBy tenant.
          type: string
        managedByTenantName:
          description: Name of the managedBy tenant.
          readOnly: true
          type: string
        provisioningState:
          description: Current state of the registration definition.
          enum:
          - NotSpecified
          - Accepted
          - Running
          - Ready
          - Creating
          - Created
          - Deleting
          - Deleted
          - Canceled
          - Failed
          - Succeeded
          - Updating
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: ProvisioningState
        registrationDefinitionName:
          description: Name of the registration definition.
          type: string
      required:
      - authorizations
      - managedByTenantId
      type: object
    ErrorResponse_error:
      description: Error response indicates Azure Resource Manager is not able to
        process the incoming request. The reason is provided in the error message.
      example:
        code: code
        message: message
      properties:
        code:
          description: Error code.
          type: string
        message:
          description: Error message indicating why the operation failed.
          type: string
      readOnly: true
      required:
      - code
      - message
      type: object
    Operation_display:
      description: The object that represents the operation.
      example:
        provider: provider
        resource: resource
        description: description
        operation: operation
      properties:
        description:
          description: Description of the operation.
          type: string
        operation:
          description: "Operation type: Read, write, delete, etc."
          type: string
        provider:
          description: "Service provider: Microsoft.ManagedServices"
          type: string
        resource:
          description: "Resource on which the operation is performed: Registration\
            \ definition, registration assignment etc."
          type: string
      readOnly: true
      type: object
    RegistrationAssignmentProperties_registrationDefinition_properties:
      description: Properties of registration definition inside registration assignment.
      example:
        manageeTenantName: manageeTenantName
        manageeTenantId: manageeTenantId
        registrationDefinitionName: registrationDefinitionName
        managedByTenantId: managedByTenantId
        authorizations:
        - roleDefinitionId: roleDefinitionId
          principalId: principalId
        - roleDefinitionId: roleDefinitionId
          principalId: principalId
        description: description
        provisioningState: NotSpecified
        managedByTenantName: managedByTenantName
      properties:
        authorizations:
          description: Authorization tuple containing principal id of the user/security
            group or service principal and id of the build-in role.
          items:
            $ref: '#/components/schemas/Authorization'
          type: array
        description:
          description: Description of the registration definition.
          type: string
        managedByTenantId:
          description: Id of the managedBy tenant.
          type: string
        managedByTenantName:
          description: Name of the managedBy tenant.
          type: string
        manageeTenantId:
          description: Id of the home tenant.
          type: string
        manageeTenantName:
          description: Name of the home tenant.
          type: string
        provisioningState:
          description: Current state of the registration definition.
          enum:
          - NotSpecified
          - Accepted
          - Running
          - Ready
          - Creating
          - Created
          - Deleting
          - Deleted
          - Canceled
          - Failed
          - Succeeded
          - Updating
          type: string
          x-ms-enum:
            modelAsString: true
            name: ProvisioningState
        registrationDefinitionName:
          description: Name of the registration definition.
          type: string
      type: object
    RegistrationAssignmentProperties_registrationDefinition:
      description: Registration definition inside registration assignment.
      example:
        name: name
        id: id
        type: type
        plan:
          product: product
          name: name
          publisher: publisher
          version: version
        properties:
          manageeTenantName: manageeTenantName
          manageeTenantId: manageeTenantId
          registrationDefinitionName: registrationDefinitionName
          managedByTenantId: managedByTenantId
          authorizations:
          - roleDefinitionId: roleDefinitionId
            principalId: principalId
          - roleDefinitionId: roleDefinitionId
            principalId: principalId
          description: description
          provisioningState: NotSpecified
          managedByTenantName: managedByTenantName
      properties:
        id:
          description: Fully qualified path of the registration definition.
          readOnly: true
          type: string
        name:
          description: Name of the registration definition.
          readOnly: true
          type: string
        plan:
          $ref: '#/components/schemas/Plan'
        properties:
          $ref: '#/components/schemas/RegistrationAssignmentProperties_registrationDefinition_properties'
        type:
          description: Type of the resource (Microsoft.ManagedServices/registrationDefinitions).
          readOnly: true
          type: string
      readOnly: true
      type: object
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
      type: oauth2
x-original-swagger-version: "2.0"

