openapi: 3.0.1
info:
  contact:
    email: support@mailsquad.com
    url: https://mailsquad.com
  description: "MailSquad offers an affordable and super easy way to create, send\
    \ and track delightful emails."
  title: Mailsquad
  version: "0.9"
  x-apisguru-categories:
  - email
  - marketing
  x-logo:
    url: https://pbs.twimg.com/profile_images/528918177711796225/5tzW9XKS.png
  x-origin:
  - format: swagger
    url: https://api.inboxroute.com/api/api-docs
    version: "2.0"
  x-providerName: inboxroute.com
servers:
- url: https://api.inboxroute.com/api
security:
- mqApiKey: []
paths:
  /contacts:
    get:
      description: Get a paged result of contacts from a list
      operationId: contacts_get
      parameters:
      - description: Unique 16 characters ID of the contact list to get contacts of
        in: query
        name: listid
        schema:
          type: string
      - description: Skip that many records
        in: query
        name: offset
        schema:
          type: integer
      - description: Maximum number of items in page
        in: query
        name: limit
        schema:
          type: integer
      - description: Property to sort by. Append '-' for descending order.
        in: query
        name: sort
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactPage'
          description: Page object
        "401":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_401_response_inner'
                type: array
          description: Invalid api key or key does not have access to this ressource
        "404":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_404_response_inner'
                type: array
          description: The requested resource was not found
        "422":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_422_response_inner'
                type: array
          description: The request parameters were invalid
      security:
      - mqApiKey: []
      tags:
      - contacts
      x-openapi-router-controller: openapi_server.controllers.contacts_controller
  /contacts/lists:
    get:
      description: Get a paged result of contact lists.
      operationId: contacts_lists_get
      parameters:
      - description: Skip that many records
        in: query
        name: offset
        schema:
          type: integer
      - description: Maximum number of items in page
        in: query
        name: limit
        schema:
          type: integer
      - description: Property to sort by. Append '-' for descending order.
        in: query
        name: sort
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactListPage'
          description: Page object
        "401":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_401_response_inner'
                type: array
          description: Invalid api key or key does not have access to this ressource
        "404":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_404_response_inner'
                type: array
          description: The requested resource was not found
        "422":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_422_response_inner'
                type: array
          description: The request parameters were invalid
      security:
      - mqApiKey: []
      tags:
      - lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
    post:
      description: Add a new contact list
      operationId: contacts_lists_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactListUpdate'
        description: Contact list initial properties
        required: false
        x-body-name: contactlist
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewId'
          description: Page object
        "401":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_401_response_inner'
                type: array
          description: Invalid api key or key does not have access to this ressource
        "422":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_422_response_inner'
                type: array
          description: The request parameters were invalid
      security:
      - mqApiKey: []
      tags:
      - lists
      x-codegen-request-body-name: contactlist
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /contacts/lists/{listid}:
    delete:
      description: Delete an existing contact list
      operationId: contacts_lists_listid_delete
      parameters:
      - description: Unique 16 characters ID of the contact list
        in: path
        name: listid
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: Empty response
        "401":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_401_response_inner'
                type: array
          description: Invalid api key or key does not have access to this ressource
        "404":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_404_response_inner'
                type: array
          description: The requested resource was not found
      security:
      - mqApiKey: []
      tags:
      - lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
    put:
      description: Update an existing contact list
      operationId: contacts_lists_listid_put
      parameters:
      - description: Unique 16 characters ID of the contact list
        in: path
        name: listid
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactListUpdate'
        description: Contact list properties to update
        required: false
        x-body-name: contactlist
      responses:
        "200":
          content: {}
          description: Empty response
        "401":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_401_response_inner'
                type: array
          description: Invalid api key or key does not have access to this ressource
        "404":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_404_response_inner'
                type: array
          description: The requested resource was not found
        "422":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_422_response_inner'
                type: array
          description: The request parameters were invalid
      security:
      - mqApiKey: []
      tags:
      - lists
      x-codegen-request-body-name: contactlist
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /contacts/{contactid}:
    delete:
      description: Delete an existing contact
      operationId: contacts_contactid_delete
      parameters:
      - description: Unique 16 characters ID of the contact
        in: path
        name: contactid
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: Empty response
        "401":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_401_response_inner'
                type: array
          description: Invalid api key or key does not have access to this ressource
        "404":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_404_response_inner'
                type: array
          description: The requested resource was not found
      security:
      - mqApiKey: []
      tags:
      - contacts
      x-openapi-router-controller: openapi_server.controllers.contacts_controller
    put:
      description: Update an existing contact
      operationId: contacts_contactid_put
      parameters:
      - description: Unique 16 characters ID of the contact
        in: path
        name: contactid
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactUpdate'
        description: Contact properties to update
        required: true
        x-body-name: contact
      responses:
        "200":
          content: {}
          description: Empty response
        "401":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_401_response_inner'
                type: array
          description: Invalid api key or key does not have access to this ressource
        "404":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_404_response_inner'
                type: array
          description: The requested resource was not found
        "422":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_422_response_inner'
                type: array
          description: The request parameters were invalid
      security:
      - mqApiKey: []
      tags:
      - contacts
      x-codegen-request-body-name: contact
      x-openapi-router-controller: openapi_server.controllers.contacts_controller
  /subscription/{listid}:
    post:
      description: |
        Subscribe an email address to a list. This api call has the same behavior as
        a regular subscribe form. However, single opt-in is allowed for system integration
        purposes.

        - If email address does not exist, a new contact will be added to the list.
        - If email address exists custom fields will be updated and status will be put
          to unconfirmed or active depending of singleoptin value.
        - If current status if Active, this operation will only update the custom fields.
        - If singleoptin is true, no email confirmation will be sent. In that case,
          you must provide the subscribe's origin ip and confirmation date-time.
      operationId: subscription_listid_post
      parameters:
      - description: Unique 16 characters ID of the contact list
        in: path
        name: listid
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionRequest'
        description: Subscription request
        required: true
        x-body-name: subscription
      responses:
        "204":
          content: {}
          description: Empty response
        "401":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_401_response_inner'
                type: array
          description: Invalid api key or key does not have access to this ressource
        "404":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_404_response_inner'
                type: array
          description: The requested resource was not found
        "422":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_contacts_get_422_response_inner'
                type: array
          description: The request parameters were invalid
      security:
      - mqApiKey: []
      tags:
      - subscription
      x-codegen-request-body-name: subscription
      x-openapi-router-controller: openapi_server.controllers.subscription_controller
components:
  responses:
    "401":
      content:
        application/json:
          schema:
            items:
              properties:
                classification:
                  description: Type of error (AccesDenied)
                  type: string
                message:
                  description: Human readable description of the error
                  type: string
              type: object
            type: array
      description: Invalid api key or key does not have access to this ressource
    "404":
      content:
        application/json:
          schema:
            items:
              properties:
                classification:
                  description: Type of error (Object not found)
                  type: string
                message:
                  description: Human readable description of the error
                  type: string
              type: object
            type: array
      description: The requested resource was not found
    "422":
      content:
        application/json:
          schema:
            items:
              properties:
                classification:
                  description: Type of error (ValidationError)
                  type: string
                message:
                  description: Human readable description of the error
                  type: string
              type: object
            type: array
      description: The request parameters were invalid
  schemas:
    Contact:
      example:
        listid: listid
        clientid: clientid
        ip: ip
        _id: _id
        fullname: fullname
        lang: lang
        confirmed: 2000-01-23T04:56:07.000+00:00
        customfields: "{}"
        email: email
        status: 0
      properties:
        _id:
          description: Unique 16 characters ID
          title: _id
          type: string
        clientid:
          description: Unique 16 characters ID of the client owner
          title: clientid
          type: string
        confirmed:
          description: Date+time subscriber confirmed his/her list opt-in
          format: date-time
          title: confirmed
          type: string
        customfields:
          description: Dictionnary of field key to value
          title: customfields
          type: object
        email:
          description: Email address
          title: email
          type: string
        fullname:
          description: |
            Full name (Last name, First Name) of the subscriber
          title: fullname
          type: string
        ip:
          description: Subscriber's IP address when he/she confirmed list opt-in
          title: ip
          type: string
        lang:
          description: "ISO 639-1 language code of the subscriber. When lang is one\
            \ the supported system language, all communication\nwill be in this language.\
            \ \n"
          title: lang
          type: string
        listid:
          description: Unique 16 characters ID of the list owner
          title: listid
          type: string
        status:
          description: |
            Status (
              1- Active,
              2- Unconfirmed,
              3- Unsubscribed,
              4- Deleted,
              5- Cleaned because of hard bounce or spam complaint)
          title: status
          type: integer
      title: Contact
      type: object
    ContactAdd:
      properties:
        confirmed:
          description: Date+time subscriber confirmed his/her list opt-in
          format: date-time
          type: string
        customfields:
          description: Dictionnary of field key to value
          type: object
        email:
          description: Email address
          type: string
        ip:
          description: Subscriber's IP address when he/she confirmed list opt-in
          type: string
        listid:
          description: Unique 16 characters ID of the list owner
          type: string
        status:
          description: |
            Status (
              1- Active,
              2- Unconfirmed,
              3- Unsubscribed,
              4- Deleted,
              5- Cleaned because of hard bounce or spam complaint)
          type: integer
      required:
      - email
      - listid
      type: object
    ContactCustomFieldSchema:
      example:
        label: label
        type: 0
        key: key
        required: true
      properties:
        key:
          description: equivalent to html form input name attribute
          title: key
          type: string
        label:
          description: User friendly label describing the field
          title: label
          type: string
        required:
          description: Is field required
          title: required
          type: boolean
        type:
          description: |
            Type (
              1- String / text free form
              2- Numeric / integer or decimal
              3- Date / ISO 8601 format (YYYY/MM/DD)
            )
          title: type
          type: integer
      required:
      - key
      - label
      - type
      title: ContactCustomFieldSchema
      type: object
    ContactList:
      example:
        clientid: clientid
        created: 2000-01-23T04:56:07.000+00:00
        name: name
        eventcustomizations:
        - redirecturl: redirecturl
          type: 6
        - redirecturl: redirecturl
          type: 6
        _id: _id
        customfields:
        - label: label
          type: 0
          key: key
          required: true
        - label: label
          type: 0
          key: key
          required: true
      properties:
        _id:
          description: Unique 16 characters ID
          title: _id
          type: string
        clientid:
          description: Unique 16 characters ID of the client owner
          title: clientid
          type: string
        created:
          format: date-time
          title: created
          type: string
        customfields:
          description: Array of ContactCustomFieldSchema
          items:
            $ref: '#/components/schemas/ContactCustomFieldSchema'
          title: customfields
          type: array
        eventcustomizations:
          description: Array of ContactListEventCustomization
          items:
            $ref: '#/components/schemas/ContactListEventCustomization'
          title: eventcustomizations
          type: array
        name:
          description: Name of the contact list
          title: name
          type: string
      title: ContactList
      type: object
    ContactListEventCustomization:
      example:
        redirecturl: redirecturl
        type: 6
      properties:
        redirecturl:
          description: full url of the destination landing page
          title: redirecturl
          type: string
        type:
          description: |
            Type (
              1- Subscribe confirmation request landing page
              2- Subscribe opt-in landing page
              3- Unsubscribe confirmation landing page
            )
          title: type
          type: integer
      required:
      - type
      title: ContactListEventCustomization
      type: object
    ContactListPage:
      example:
        total: 1
        page:
        - clientid: clientid
          created: 2000-01-23T04:56:07.000+00:00
          name: name
          eventcustomizations:
          - redirecturl: redirecturl
            type: 6
          - redirecturl: redirecturl
            type: 6
          _id: _id
          customfields:
          - label: label
            type: 0
            key: key
            required: true
          - label: label
            type: 0
            key: key
            required: true
        - clientid: clientid
          created: 2000-01-23T04:56:07.000+00:00
          name: name
          eventcustomizations:
          - redirecturl: redirecturl
            type: 6
          - redirecturl: redirecturl
            type: 6
          _id: _id
          customfields:
          - label: label
            type: 0
            key: key
            required: true
          - label: label
            type: 0
            key: key
            required: true
      properties:
        page:
          description: Array of ContactList for that page
          items:
            $ref: '#/components/schemas/ContactList'
          title: page
          type: array
        total:
          description: Total number of items in query
          title: total
          type: integer
      title: ContactListPage
      type: object
    ContactListUpdate:
      example:
        name: name
        eventcustomizations:
        - redirecturl: redirecturl
          type: 6
        - redirecturl: redirecturl
          type: 6
        customfields:
        - label: label
          type: 0
          key: key
          required: true
        - label: label
          type: 0
          key: key
          required: true
      properties:
        customfields:
          description: Array of ContactCustomFieldSchema
          items:
            $ref: '#/components/schemas/ContactCustomFieldSchema'
          title: customfields
          type: array
        eventcustomizations:
          description: Array of ContactListEventCustomization
          items:
            $ref: '#/components/schemas/ContactListEventCustomization'
          title: eventcustomizations
          type: array
        name:
          description: Name of the contact list
          title: name
          type: string
      title: ContactListUpdate
      type: object
    ContactPage:
      example:
        total: 6
        page:
        - listid: listid
          clientid: clientid
          ip: ip
          _id: _id
          fullname: fullname
          lang: lang
          confirmed: 2000-01-23T04:56:07.000+00:00
          customfields: "{}"
          email: email
          status: 0
        - listid: listid
          clientid: clientid
          ip: ip
          _id: _id
          fullname: fullname
          lang: lang
          confirmed: 2000-01-23T04:56:07.000+00:00
          customfields: "{}"
          email: email
          status: 0
      properties:
        page:
          description: Array of Contact for that page
          items:
            $ref: '#/components/schemas/Contact'
          title: page
          type: array
        total:
          description: Total number of items in query
          title: total
          type: integer
      title: ContactPage
      type: object
    ContactUpdate:
      example:
        ip: ip
        confirmed: 2000-01-23T04:56:07.000+00:00
        customfields: "{}"
        email: email
        status: 0
      properties:
        confirmed:
          description: Date+time subscriber confirmed his/her list opt-in
          format: date-time
          title: confirmed
          type: string
        customfields:
          description: Dictionnary of field key to value
          title: customfields
          type: object
        email:
          description: Email address
          title: email
          type: string
        ip:
          description: Subscriber's IP address when he/she confirmed list opt-in
          title: ip
          type: string
        status:
          description: |
            Status (
              1- Active,
              2- Unconfirmed,
              3- Unsubscribed,
              4- Deleted,
              5- Cleaned because of hard bounce or spam complaint)
          title: status
          type: integer
      title: ContactUpdate
      type: object
    NewId:
      example:
        _id: _id
      properties:
        _id:
          description: The created ressource id
          title: _id
          type: string
      title: NewId
      type: object
    SubscriptionRequest:
      example:
        ip: ip
        singleoptin: true
        fullname: fullname
        lang: lang
        confirmed: 2000-01-23T04:56:07.000+00:00
        email: email
      properties:
        confirmed:
          description: Date-time when subscriber opted-in. Required if singleoptin
            is true.
          format: date-time
          title: confirmed
          type: string
        email:
          description: Email address of the subscriber
          title: email
          type: string
        fullname:
          description: |
            Full name (Last name, First Name) of the subscriber
          title: fullname
          type: string
        ip:
          description: Origin Ip of the subscriber when he/she opted-in. Required
            if singleoptin is true.
          title: ip
          type: string
        lang:
          description: |
            ISO 639-1 language code of the subscriber. When lang is one the supported system language, all communication
            will be in this language.
          title: lang
          type: string
        singleoptin:
          description: |
            If true, no email will be sent asking user subscription confirmation. In that case, you must provide
            the confirmation date (confirmed) and origin ip (ip) manually.
          title: singleoptin
          type: boolean
      required:
      - email
      title: SubscriptionRequest
      type: object
    _contacts_get_401_response_inner:
      example:
        classification: classification
        message: message
      properties:
        classification:
          description: Type of error (AccesDenied)
          title: classification
          type: string
        message:
          description: Human readable description of the error
          title: message
          type: string
      title: _contacts_get_401_response_inner
      type: object
    _contacts_get_404_response_inner:
      example:
        classification: classification
        message: message
      properties:
        classification:
          description: Type of error (Object not found)
          title: classification
          type: string
        message:
          description: Human readable description of the error
          title: message
          type: string
      title: _contacts_get_404_response_inner
      type: object
    _contacts_get_422_response_inner:
      example:
        classification: classification
        message: message
      properties:
        classification:
          description: Type of error (ValidationError)
          title: classification
          type: string
        message:
          description: Human readable description of the error
          title: message
          type: string
      title: _contacts_get_422_response_inner
      type: object
  securitySchemes:
    mqApiKey:
      in: header
      name: Authorization
      type: apiKey
      x-apikeyInfoFunc: openapi_server.controllers.security_controller.info_from_mqApiKey
x-original-swagger-version: "2.0"
