openapi: 3.0.1
info:
  title: AzureStack Azure Bridge Client
  version: 2017-06-01
  x-apisguru-categories:
  - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
  - format: swagger
    url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azurestack/resource-manager/Microsoft.AzureStack/stable/2017-06-01/Product.json
    version: "2.0"
  x-providerName: azure.com
  x-serviceName: azurestack-Product
  x-tags:
  - Azure
  - Microsoft
servers:
- url: https://management.azure.com/
security:
- azure_auth:
  - user_impersonation
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.AzureStack/registrations/{registrationName}/products
  : get:
      description: Returns a list of products.
      operationId: Products_List
      parameters:
      - description: Subscription credentials that uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
      - description: Name of the resource group.
        in: path
        name: resourceGroup
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the Azure Stack registration.
        in: path
        name: registrationName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Client API Version.
        in: query
        name: api-version
        required: true
        schema:
          default: 2017-06-01
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products_List_default_response'
          description: Error response describing why the operation failed.
      tags:
      - Product
      x-ms-examples:
        Returns a list of products.:
          parameters:
            api-version: 2017-06-01
            registrationName: testregistration
            resourceGroup: azurestack
            subscriptionId: dd8597b4-8739-4467-8b10-f8679f62bfbf
          responses:
            "200":
              body:
                value:
                - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
                  name: testregistration/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
                  properties:
                    displayName: VM Access For Linux Extension
                    galleryItemIdentity: Microsoft.VMAccessForLinux.1.4.7
                    iconUris:
                      large: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Large.png
                      medium: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Medium.png
                      small: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Small.png
                      wide: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Wide.png
                    offer: ""
                    offerVersion: ""
                    payloadLength: 46959
                    productKind: virtualMachineExtension
                    productProperties:
                      version: 1.4.7
                    publisherDisplayName: Microsoft Corp.
                    publisherIdentifier: Microsoft.OSTCExtensions
                    sku: ""
                    vmExtensionType: VMAccessForLinux
                  type: Microsoft.AzureStack/registrations/products
                - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/dummysharepoint
                  name: testregistration/dummysharepoint
                  properties:
                    displayName: Display name for dummy SharePoint
                    galleryItemIdentity: Microsoft.SharePointServer2013Trial-ARM.1.0.3
                    iconUris:
                      hero: https://extensions.azureedge.net/dummysharepoint/icons/Hero.png
                      large: https://extensions.azureedge.net/dummysharepoint/icons/Large.png
                      medium: https://extensions.azureedge.net/dummysharepoint/icons/Medium.png
                      small: https://extensions.azureedge.net/dummysharepoint/icons/Small.png
                      wide: https://extensions.azureedge.net/dummysharepoint/icons/Wide.png
                    offer: Dummy offer
                    offerVersion: "FakeProduct: offer version"
                    payloadLength: 4682158
                    productKind: virtualMachine
                    productProperties:
                      version: 1.0.1
                    publisherDisplayName: Publisher display name for dummy SharePoint
                    publisherIdentifier: Katal
                    sku: Dummy sku
                  type: Microsoft.AzureStack/registrations/products
                - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/dummysharepointTest526
                  name: testregistration/dummysharepointTest526
                  properties:
                    displayName: Display name for dummy SharePoint
                    galleryItemIdentity: Microsoft.SharePointServer2013Trial-ARM.1.0.3
                    iconUris:
                      hero: https://extensions.azureedge.net/dummysharepointTest526/icons/Hero.png
                      large: https://extensions.azureedge.net/dummysharepointTest526/icons/Large.png
                      medium: https://extensions.azureedge.net/dummysharepointTest526/icons/Medium.png
                      small: https://extensions.azureedge.net/dummysharepointTest526/icons/Small.png
                      wide: https://extensions.azureedge.net/dummysharepointTest526/icons/Wide.png
                    offer: Dummy offer
                    offerVersion: "FakeProduct: offer version"
                    payloadLength: 4682158
                    productKind: virtualMachine
                    productProperties:
                      version: 2.0.2
                    publisherDisplayName: Publisher display name for dummy SharePoint
                    publisherIdentifier: Katal
                    sku: Dummy sku
                  type: Microsoft.AzureStack/registrations/products
                - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d
                  name: testregistration/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d
                  properties:
                    displayName: Display name for dummy SharePoint
                    galleryItemIdentity: Microsoft.SharePointServer2013Trial-ARM.1.0.3
                    iconUris:
                      hero: https://extensions.azureedge.net/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d/icons/Hero.png
                      large: https://extensions.azureedge.net/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d/icons/Large.png
                      medium: https://extensions.azureedge.net/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d/icons/Medium.png
                      small: https://extensions.azureedge.net/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d/icons/Small.png
                      wide: https://extensions.azureedge.net/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d/icons/Wide.png
                    offer: Dummy offer
                    offerVersion: "FakeProduct: offer version"
                    payloadLength: 4682158
                    productKind: virtualMachine
                    productProperties:
                      version: 1.0.1
                    publisherDisplayName: Publisher display name for dummy SharePoint
                    publisherIdentifier: Katal
                    sku: Dummy sku
                  type: Microsoft.AzureStack/registrations/products
                - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/wordpress4-4
                  name: testregistration/wordpress4-4
                  properties:
                    displayName: WordPress
                    galleryItemIdentity: bitnami.wordpress4-4.1.0.8
                    iconUris:
                      hero: https://extensions.azureedge.net/wordpress4-4/icons/Hero.png
                      large: https://extensions.azureedge.net/wordpress4-4/icons/Large.png
                      medium: https://extensions.azureedge.net/wordpress4-4/icons/Medium.png
                      small: https://extensions.azureedge.net/wordpress4-4/icons/Small.png
                      wide: https://extensions.azureedge.net/wordpress4-4/icons/Wide.png
                    offer: wordpress
                    offerVersion: 1.0.8
                    payloadLength: 32212604365
                    productKind: virtualMachine
                    productProperties:
                      version: 4.5.31
                    publisherDisplayName: WordPress
                    publisherIdentifier: bitnami
                    sku: 4-4
                  type: Microsoft.AzureStack/registrations/products
      x-ms-pageable:
        nextLinkName: nextLink
      x-accepts:
      - application/json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.AzureStack/registrations/{registrationName}/products/_all/GetProducts
  : post:
      description: Returns a list of products.
      operationId: Products_GetProducts
      parameters:
      - description: Subscription credentials that uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
      - description: Name of the resource group.
        in: path
        name: resourceGroup
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the Azure Stack registration.
        in: path
        name: registrationName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Client API Version.
        in: query
        name: api-version
        required: true
        schema:
          default: 2017-06-01
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceConfiguration'
        description: Device configuration.
        required: false
        x-ms-parameter-location: method
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products_List_default_response'
          description: Error response describing why the operation failed.
      tags:
      - Product
      x-ms-examples:
        Returns a list of products.:
          parameters:
            api-version: 2017-06-01
            deviceConfiguration:
              deviceVersion: 1910.0.0.0
              identitySystem: AzureAD
            registrationName: testregistration
            resourceGroup: azurestack
            subscriptionId: dd8597b4-8739-4467-8b10-f8679f62bfbf
          responses:
            "200":
              body:
                value:
                - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
                  name: testregistration/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
                  properties:
                    compatibility:
                      description: ""
                      isCompatible: true
                      issues: []
                      message: ""
                    displayName: VM Access For Linux Extension
                    galleryItemIdentity: Microsoft.VMAccessForLinux.1.4.7
                    iconUris:
                      large: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Large.png
                      medium: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Medium.png
                      small: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Small.png
                      wide: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Wide.png
                    offer: ""
                    offerVersion: ""
                    payloadLength: 46959
                    productKind: virtualMachineExtension
                    productProperties:
                      version: 1.4.7
                    publisherDisplayName: Microsoft Corp.
                    publisherIdentifier: Microsoft.OSTCExtensions
                    sku: ""
                    vmExtensionType: VMAccessForLinux
                  type: Microsoft.AzureStack/registrations/products
                - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/dummysharepoint
                  name: testregistration/dummysharepoint
                  properties:
                    compatibility:
                      description: ""
                      isCompatible: true
                      issues: []
                      message: ""
                    displayName: Display name for dummy SharePoint
                    galleryItemIdentity: Microsoft.SharePointServer2013Trial-ARM.1.0.3
                    iconUris:
                      hero: https://extensions.azureedge.net/dummysharepoint/icons/Hero.png
                      large: https://extensions.azureedge.net/dummysharepoint/icons/Large.png
                      medium: https://extensions.azureedge.net/dummysharepoint/icons/Medium.png
                      small: https://extensions.azureedge.net/dummysharepoint/icons/Small.png
                      wide: https://extensions.azureedge.net/dummysharepoint/icons/Wide.png
                    offer: Dummy offer
                    offerVersion: "FakeProduct: offer version"
                    payloadLength: 4682158
                    productKind: virtualMachine
                    productProperties:
                      version: 1.0.1
                    publisherDisplayName: Publisher display name for dummy SharePoint
                    publisherIdentifier: Katal
                    sku: Dummy sku
                  type: Microsoft.AzureStack/registrations/products
                - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/dummysharepointTest526
                  name: testregistration/dummysharepointTest526
                  properties:
                    compatibility:
                      description: ""
                      isCompatible: true
                      issues: []
                      message: ""
                    displayName: Display name for dummy SharePoint
                    galleryItemIdentity: Microsoft.SharePointServer2013Trial-ARM.1.0.3
                    iconUris:
                      hero: https://extensions.azureedge.net/dummysharepointTest526/icons/Hero.png
                      large: https://extensions.azureedge.net/dummysharepointTest526/icons/Large.png
                      medium: https://extensions.azureedge.net/dummysharepointTest526/icons/Medium.png
                      small: https://extensions.azureedge.net/dummysharepointTest526/icons/Small.png
                      wide: https://extensions.azureedge.net/dummysharepointTest526/icons/Wide.png
                    offer: Dummy offer
                    offerVersion: "FakeProduct: offer version"
                    payloadLength: 4682158
                    productKind: virtualMachine
                    productProperties:
                      version: 2.0.2
                    publisherDisplayName: Publisher display name for dummy SharePoint
                    publisherIdentifier: Katal
                    sku: Dummy sku
                  type: Microsoft.AzureStack/registrations/products
                - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d
                  name: testregistration/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d
                  properties:
                    compatibility:
                      description: ""
                      isCompatible: true
                      issues: []
                      message: ""
                    displayName: Display name for dummy SharePoint
                    galleryItemIdentity: Microsoft.SharePointServer2013Trial-ARM.1.0.3
                    iconUris:
                      hero: https://extensions.azureedge.net/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d/icons/Hero.png
                      large: https://extensions.azureedge.net/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d/icons/Large.png
                      medium: https://extensions.azureedge.net/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d/icons/Medium.png
                      small: https://extensions.azureedge.net/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d/icons/Small.png
                      wide: https://extensions.azureedge.net/test.product.976fe55e-6921-47bb-b8ba-718bba70c72d/icons/Wide.png
                    offer: Dummy offer
                    offerVersion: "FakeProduct: offer version"
                    payloadLength: 4682158
                    productKind: virtualMachine
                    productProperties:
                      version: 1.0.1
                    publisherDisplayName: Publisher display name for dummy SharePoint
                    publisherIdentifier: Katal
                    sku: Dummy sku
                  type: Microsoft.AzureStack/registrations/products
                - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/wordpress4-4
                  name: testregistration/wordpress4-4
                  properties:
                    compatibility:
                      description: AzureStack version '1910.0.0.0' is too low. Versions
                        lower than '1911.0.0.0' are not supported
                      isCompatible: false
                      issues:
                      - HigherDeviceVersionRequired
                      message: AzureStack version '1910.0.0.0' is too low. Versions
                        lower than '1911.0.0.0' are not supported
                    displayName: WordPress
                    galleryItemIdentity: bitnami.wordpress4-4.1.0.8
                    iconUris:
                      hero: https://extensions.azureedge.net/wordpress4-4/icons/Hero.png
                      large: https://extensions.azureedge.net/wordpress4-4/icons/Large.png
                      medium: https://extensions.azureedge.net/wordpress4-4/icons/Medium.png
                      small: https://extensions.azureedge.net/wordpress4-4/icons/Small.png
                      wide: https://extensions.azureedge.net/wordpress4-4/icons/Wide.png
                    offer: wordpress
                    offerVersion: 1.0.8
                    payloadLength: 32212604365
                    productKind: virtualMachine
                    productProperties:
                      version: 4.5.31
                    publisherDisplayName: WordPress
                    publisherIdentifier: bitnami
                    sku: 4-4
                  type: Microsoft.AzureStack/registrations/products
      x-codegen-request-body-name: deviceConfiguration
      x-content-type: application/json
      x-accepts:
      - application/json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.AzureStack/registrations/{registrationName}/products/{productName}
  : get:
      description: Returns the specified product.
      operationId: Products_Get
      parameters:
      - description: Subscription credentials that uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
      - description: Name of the resource group.
        in: path
        name: resourceGroup
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the Azure Stack registration.
        in: path
        name: registrationName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the product.
        in: path
        name: productName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Client API Version.
        in: query
        name: api-version
        required: true
        schema:
          default: 2017-06-01
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products_List_default_response'
          description: Error response describing why the operation failed.
      tags:
      - Product
      x-ms-examples:
        Returns the specified product.:
          parameters:
            api-version: 2017-06-01
            productName: Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
            registrationName: testregistration
            resourceGroup: azurestack
            subscriptionId: dd8597b4-8739-4467-8b10-f8679f62bfbf
          responses:
            "200":
              body:
                id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
                name: testregistration/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
                properties:
                  displayName: VM Access For Linux Extension
                  galleryItemIdentity: Microsoft.VMAccessForLinux.1.4.7
                  iconUris:
                    large: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Large.png
                    medium: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Medium.png
                    small: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Small.png
                    wide: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Wide.png
                  offer: ""
                  offerVersion: ""
                  payloadLength: 46959
                  productKind: virtualMachineExtension
                  productProperties:
                    version: 1.4.7
                  publisherDisplayName: Microsoft Corp.
                  publisherIdentifier: Microsoft.OSTCExtensions
                  sku: ""
                  vmExtensionType: VMAccessForLinux
                type: Microsoft.AzureStack/registrations/products
      x-accepts:
      - application/json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.AzureStack/registrations/{registrationName}/products/{productName}/GetProduct
  : post:
      description: Returns the specified product.
      operationId: Products_GetProduct
      parameters:
      - description: Subscription credentials that uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
      - description: Name of the resource group.
        in: path
        name: resourceGroup
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the Azure Stack registration.
        in: path
        name: registrationName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the product.
        in: path
        name: productName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Client API Version.
        in: query
        name: api-version
        required: true
        schema:
          default: 2017-06-01
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceConfiguration'
        description: Device configuration.
        required: false
        x-ms-parameter-location: method
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products_List_default_response'
          description: Error response describing why the operation failed.
      tags:
      - Product
      x-ms-examples:
        Returns the specified product.:
          parameters:
            api-version: 2017-06-01
            deviceConfiguration:
              deviceVersion: 1910.0.0.0
              identitySystem: AzureAD
            productName: Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
            registrationName: testregistration
            resourceGroup: azurestack
            subscriptionId: dd8597b4-8739-4467-8b10-f8679f62bfbf
          responses:
            "200":
              body:
                id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/products/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
                name: testregistration/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
                properties:
                  compatibility:
                    description: ""
                    isCompatible: true
                    issues: []
                    message: ""
                  displayName: VM Access For Linux Extension
                  galleryItemIdentity: Microsoft.VMAccessForLinux.1.4.7
                  iconUris:
                    large: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Large.png
                    medium: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Medium.png
                    small: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Small.png
                    wide: https://extensions.azureedge.net/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/icons/Wide.png
                  offer: ""
                  offerVersion: ""
                  payloadLength: 46959
                  productKind: virtualMachineExtension
                  productProperties:
                    version: 1.4.7
                  publisherDisplayName: Microsoft Corp.
                  publisherIdentifier: Microsoft.OSTCExtensions
                  sku: ""
                  vmExtensionType: VMAccessForLinux
                type: Microsoft.AzureStack/registrations/products
      x-codegen-request-body-name: deviceConfiguration
      x-content-type: application/json
      x-accepts:
      - application/json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.AzureStack/registrations/{registrationName}/products/{productName}/listDetails
  : post:
      description: Returns the extended properties of a product.
      operationId: Products_ListDetails
      parameters:
      - description: Subscription credentials that uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
      - description: Name of the resource group.
        in: path
        name: resourceGroup
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the Azure Stack registration.
        in: path
        name: registrationName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the product.
        in: path
        name: productName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Client API Version.
        in: query
        name: api-version
        required: true
        schema:
          default: 2017-06-01
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtendedProduct'
          description: OK
      tags:
      - Product
      x-ms-examples:
        Returns the extended properties of a product.:
          parameters:
            api-version: 2017-06-01
            productName: Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
            registrationName: testregistration
            resourceGroup: azurestack
            subscriptionId: dd8597b4-8739-4467-8b10-f8679f62bfbf
          responses:
            "200":
              body:
                galleryPackageBlobSasUri: https://azstrptestwcu001.blob.core.windows.net/packages/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/gallery/package.azpkg?sv=2015-04-05&sr=b&sig=mnzKeDrSMWoDilUrfrETb7n%2BG0Shme6f3AYzl3uzkYA%3D&se=2018-02-13T10%3A46%3A24Z&sp=r
                productKind: virtualMachineExtension
                properties:
                  computeRole: IaaS
                  isSystemExtension: false
                  sourceBlob:
                    uri: https://azstrptestwcu001.blob.core.windows.net/packages/Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1/extension/vmext.zip?sv=2015-04-05&sr=b&sig=XtLzuO2rlqxyZOzfoTEDZW4DU9OxBZVCOw%2FVgY2%2FiUo%3D&se=2018-02-13T10%3A46%3A24Z&sp=r
                  supportMultipleExtensions: false
                  version: 1.4.7
                  vmOsType: Linux
                  vmScaleSetEnabled: false
      x-accepts:
      - application/json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.AzureStack/registrations/{registrationName}/products/{productName}/uploadProductLog
  : post:
      description: Returns the specified product.
      operationId: Products_UploadLog
      parameters:
      - description: Subscription credentials that uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
      - description: Name of the resource group.
        in: path
        name: resourceGroup
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the Azure Stack registration.
        in: path
        name: registrationName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the product.
        in: path
        name: productName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Client API Version.
        in: query
        name: api-version
        required: true
        schema:
          default: 2017-06-01
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketplaceProductLogUpdate'
        description: Update details for product log.
        required: false
        x-ms-parameter-location: method
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductLog'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products_List_default_response'
          description: Error response describing why the operation failed.
      tags:
      - Product
      x-ms-examples:
        Returns the specified product.:
          parameters:
            api-version: 2017-06-01
            marketplaceProductLogUpdate:
              details: ExampleDetails
              error: ExampleError
              operation: Download
              status: Failed
            productName: Microsoft.OSTCExtensions.VMAccessForLinux.1.4.7.1
            registrationName: testregistration
            resourceGroup: azurestack
            subscriptionId: dd8597b4-8739-4467-8b10-f8679f62bfbf
          responses:
            "200":
              body:
                details: ExampleDetails
                endDate: 01-02-2019 00:00:00
                error: ExampleError
                operation: Download
                productId: dummyProduct-1.1
                registrationName: TestCIRegistration007
                resourceGroupName: AzureStack007
                startDate: 01-01-2019 00:00:00
                status: Failed
                subscriptionId: 64D0A64B4F694EB4B0ED92BC34D98082
      x-codegen-request-body-name: marketplaceProductLogUpdate
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  parameters:
    ProductNameParameter:
      description: Name of the product.
      in: path
      name: productName
      required: true
      schema:
        type: string
        x-ms-parameter-location: method
      x-ms-parameter-location: method
  requestBodies:
    DeviceConfigurationParameter:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceConfiguration'
      description: Device configuration.
      required: false
      x-ms-parameter-location: method
    MarketplaceProductLogUpdateParameter:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MarketplaceProductLogUpdate'
      description: Update details for product log.
      required: false
      x-ms-parameter-location: method
  schemas:
    Compatibility:
      description: Product compatibility
      example:
        description: description
        message: message
        issues:
        - HigherDeviceVersionRequired
        - HigherDeviceVersionRequired
        isCompatible: true
      properties:
        description:
          description: Full error message if any compatibility issues are found
          type: string
        isCompatible:
          description: Tells if product is compatible with current device
          type: boolean
        issues:
          description: List of all issues found
          items:
            $ref: '#/components/schemas/CompatibilityIssue'
          type: array
        message:
          description: Short error message if any compatibility issues are found
          type: string
      type: object
    CompatibilityIssue:
      description: Compatibility issue
      enum:
      - HigherDeviceVersionRequired
      - LowerDeviceVersionRequired
      - CapacityBillingModelRequired
      - PayAsYouGoBillingModelRequired
      - DevelopmentBillingModelRequired
      - AzureADIdentitySystemRequired
      - ADFSIdentitySystemRequired
      - ConnectionToInternetRequired
      - ConnectionToAzureRequired
      - DisconnectedEnvironmentRequired
      type: string
      x-ms-enum:
        modelAsString: true
        name: CompatibilityIssue
    ComputeRole:
      description: Compute role type (IaaS or PaaS).
      enum:
      - None
      - IaaS
      - PaaS
      type: string
      x-ms-enum:
        modelAsString: true
        name: ComputeRole
    DataDiskImage:
      description: Data disk image.
      example:
        sourceBlobSasUri: sourceBlobSasUri
        lun: 0
      properties:
        lun:
          description: The LUN.
          format: int32
          readOnly: true
          type: integer
        sourceBlobSasUri:
          description: SAS key for source blob.
          readOnly: true
          type: string
      type: object
    DeviceConfiguration:
      description: Device Configuration.
      example:
        identitySystem: AzureAD
        deviceVersion: deviceVersion
      properties:
        deviceVersion:
          description: Version of the device.
          readOnly: true
          type: string
        identitySystem:
          description: Identity system of the device.
          enum:
          - AzureAD
          - ADFS
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: category
      type: object
    ExtendedProduct:
      description: Extended description about the product required for installing
        it into Azure Stack.
      example:
        productKind: productKind
        galleryPackageBlobSasUri: galleryPackageBlobSasUri
        properties:
          sourceBlob:
            uri: uri
          osDiskImage:
            sourceBlobSasUri: sourceBlobSasUri
            operatingSystem: null
          isSystemExtension: true
          vmScaleSetEnabled: true
          vmOsType: None
          computeRole: None
          dataDiskImages:
          - sourceBlobSasUri: sourceBlobSasUri
            lun: 0
          - sourceBlobSasUri: sourceBlobSasUri
            lun: 0
          supportMultipleExtensions: true
          version: version
      properties:
        galleryPackageBlobSasUri:
          description: The URI to the .azpkg file that provides information required
            for showing product in the gallery.
          readOnly: true
          type: string
        productKind:
          description: Specifies the kind of the product (virtualMachine or virtualMachineExtension).
          readOnly: true
          type: string
        properties:
          $ref: '#/components/schemas/ExtendedProductProperties'
      type: object
    ExtendedProductProperties:
      allOf:
      - $ref: '#/components/schemas/VirtualMachineExtensionProductProperties'
      - $ref: '#/components/schemas/VirtualMachineProductProperties'
      description: Product information.
      example:
        sourceBlob:
          uri: uri
        osDiskImage:
          sourceBlobSasUri: sourceBlobSasUri
          operatingSystem: null
        isSystemExtension: true
        vmScaleSetEnabled: true
        vmOsType: None
        computeRole: None
        dataDiskImages:
        - sourceBlobSasUri: sourceBlobSasUri
          lun: 0
        - sourceBlobSasUri: sourceBlobSasUri
          lun: 0
        supportMultipleExtensions: true
        version: version
    IconUris:
      description: Links to product icons.
      example:
        small: small
        large: large
        wide: wide
        hero: hero
        medium: medium
      properties:
        hero:
          description: URI to hero icon.
          type: string
        large:
          description: URI to large icon.
          type: string
        medium:
          description: URI to medium icon.
          type: string
        small:
          description: URI to small icon.
          type: string
        wide:
          description: URI to wide icon.
          type: string
      type: object
    MarketplaceProductLogUpdate:
      description: Update details for product log.
      example:
        details: details
        error: error
        operation: operation
        status: status
      properties:
        details:
          description: Error details related to operation.
          readOnly: true
          type: string
        error:
          description: Error related to the operation.
          readOnly: true
          type: string
        operation:
          description: Operation to log.
          readOnly: true
          type: string
        status:
          description: Operation status to log.
          readOnly: true
          type: string
      type: object
    OperatingSystem:
      description: Operating system type (Windows or Linux).
      enum:
      - None
      - Windows
      - Linux
      type: string
      x-ms-enum:
        modelAsString: true
        name: OperatingSystem
    OsDiskImage:
      description: OS disk image.
      example:
        sourceBlobSasUri: sourceBlobSasUri
        operatingSystem: null
      properties:
        operatingSystem:
          $ref: '#/components/schemas/OperatingSystem'
        sourceBlobSasUri:
          description: SAS key for source blob.
          readOnly: true
          type: string
      type: object
    Product:
      allOf:
      - description: Base resource object.
        properties:
          etag:
            description: The entity tag used for optimistic concurrency when modifying
              the resource.
            type: string
          id:
            description: ID of the resource.
            readOnly: true
            type: string
          name:
            description: Name of the resource.
            readOnly: true
            type: string
          type:
            description: Type of Resource.
            readOnly: true
            type: string
        type: object
        x-ms-azure-resource: true
      description: Product information.
      example:
        properties:
          offerVersion: offerVersion
          publisherDisplayName: publisherDisplayName
          payloadLength: 0
          productProperties:
            version: version
          iconUris:
            small: small
            large: large
            wide: wide
            hero: hero
            medium: medium
          legalTerms: legalTerms
          displayName: displayName
          privacyPolicy: privacyPolicy
          description: description
          publisherIdentifier: publisherIdentifier
          offer: offer
          productKind: productKind
          galleryItemIdentity: galleryItemIdentity
          links:
          - displayName: displayName
            uri: uri
          - displayName: displayName
            uri: uri
          billingPartNumber: billingPartNumber
          sku: sku
          compatibility:
            description: description
            message: message
            issues:
            - HigherDeviceVersionRequired
            - HigherDeviceVersionRequired
            isCompatible: true
          vmExtensionType: vmExtensionType
      properties:
        properties:
          $ref: '#/components/schemas/ProductNestedProperties'
    ProductLink:
      description: Link with additional information about a product.
      example:
        displayName: displayName
        uri: uri
      properties:
        displayName:
          description: The description of the link.
          type: string
        uri:
          description: The URI corresponding to the link.
          type: string
      type: object
    ProductList:
      description: Pageable list of products.
      example:
        value:
        - properties:
            offerVersion: offerVersion
            publisherDisplayName: publisherDisplayName
            payloadLength: 0
            productProperties:
              version: version
            iconUris:
              small: small
              large: large
              wide: wide
              hero: hero
              medium: medium
            legalTerms: legalTerms
            displayName: displayName
            privacyPolicy: privacyPolicy
            description: description
            publisherIdentifier: publisherIdentifier
            offer: offer
            productKind: productKind
            galleryItemIdentity: galleryItemIdentity
            links:
            - displayName: displayName
              uri: uri
            - displayName: displayName
              uri: uri
            billingPartNumber: billingPartNumber
            sku: sku
            compatibility:
              description: description
              message: message
              issues:
              - HigherDeviceVersionRequired
              - HigherDeviceVersionRequired
              isCompatible: true
            vmExtensionType: vmExtensionType
        - properties:
            offerVersion: offerVersion
            publisherDisplayName: publisherDisplayName
            payloadLength: 0
            productProperties:
              version: version
            iconUris:
              small: small
              large: large
              wide: wide
              hero: hero
              medium: medium
            legalTerms: legalTerms
            displayName: displayName
            privacyPolicy: privacyPolicy
            description: description
            publisherIdentifier: publisherIdentifier
            offer: offer
            productKind: productKind
            galleryItemIdentity: galleryItemIdentity
            links:
            - displayName: displayName
              uri: uri
            - displayName: displayName
              uri: uri
            billingPartNumber: billingPartNumber
            sku: sku
            compatibility:
              description: description
              message: message
              issues:
              - HigherDeviceVersionRequired
              - HigherDeviceVersionRequired
              isCompatible: true
            vmExtensionType: vmExtensionType
        nextLink: nextLink
      properties:
        nextLink:
          description: URI to the next page.
          type: string
        value:
          description: List of products.
          items:
            $ref: '#/components/schemas/Product'
          type: array
      type: object
    ProductLog:
      description: Product action log.
      example:
        resourceGroupName: resourceGroupName
        productId: productId
        endDate: endDate
        registrationName: registrationName
        details: details
        id: id
        error: error
        subscriptionId: subscriptionId
        operation: operation
        startDate: startDate
        status: status
      properties:
        details:
          description: Operation error details.
          readOnly: true
          type: string
        endDate:
          description: Operation end datetime.
          readOnly: true
          type: string
        error:
          description: Operation error data.
          readOnly: true
          type: string
        id:
          description: Log ID.
          readOnly: true
          type: string
        operation:
          description: Logged operation.
          readOnly: true
          type: string
        productId:
          description: Logged product ID.
          readOnly: true
          type: string
        registrationName:
          description: Logged registration name.
          readOnly: true
          type: string
        resourceGroupName:
          description: Logged resource group name.
          readOnly: true
          type: string
        startDate:
          description: Operation start datetime.
          readOnly: true
          type: string
        status:
          description: Operation status.
          readOnly: true
          type: string
        subscriptionId:
          description: Logged subscription ID.
          readOnly: true
          type: string
      type: object
    ProductNestedProperties:
      description: Properties portion of the product resource.
      example:
        offerVersion: offerVersion
        publisherDisplayName: publisherDisplayName
        payloadLength: 0
        productProperties:
          version: version
        iconUris:
          small: small
          large: large
          wide: wide
          hero: hero
          medium: medium
        legalTerms: legalTerms
        displayName: displayName
        privacyPolicy: privacyPolicy
        description: description
        publisherIdentifier: publisherIdentifier
        offer: offer
        productKind: productKind
        galleryItemIdentity: galleryItemIdentity
        links:
        - displayName: displayName
          uri: uri
        - displayName: displayName
          uri: uri
        billingPartNumber: billingPartNumber
        sku: sku
        compatibility:
          description: description
          message: message
          issues:
          - HigherDeviceVersionRequired
          - HigherDeviceVersionRequired
          isCompatible: true
        vmExtensionType: vmExtensionType
      properties:
        billingPartNumber:
          description: The part number used for billing purposes.
          type: string
        compatibility:
          $ref: '#/components/schemas/Compatibility'
        description:
          description: The description of the product.
          type: string
        displayName:
          description: The display name of the product.
          type: string
        galleryItemIdentity:
          description: The identifier of the gallery item corresponding to the product.
          type: string
        iconUris:
          $ref: '#/components/schemas/IconUris'
        legalTerms:
          description: The legal terms.
          type: string
        links:
          description: Additional links available for this product.
          items:
            $ref: '#/components/schemas/ProductLink'
          type: array
        offer:
          description: The offer representing the product.
          type: string
        offerVersion:
          description: The version of the product offer.
          type: string
        payloadLength:
          description: The length of product content.
          format: int64
          type: integer
        privacyPolicy:
          description: The privacy policy.
          type: string
        productKind:
          description: The kind of the product (virtualMachine or virtualMachineExtension)
          type: string
        productProperties:
          $ref: '#/components/schemas/ProductProperties'
        publisherDisplayName:
          description: The user-friendly name of the product publisher.
          type: string
        publisherIdentifier:
          description: Publisher identifier.
          type: string
        sku:
          description: The product SKU.
          type: string
        vmExtensionType:
          description: The type of the Virtual Machine Extension.
          type: string
      type: object
    ProductProperties:
      description: Additional properties of the product
      example:
        version: version
      properties:
        version:
          description: The version.
          type: string
      type: object
    Uri:
      description: The URI.
      example:
        uri: uri
      properties:
        uri:
          description: The URI.
          readOnly: true
          type: string
      type: object
    VirtualMachineExtensionProductProperties:
      description: Product information.
      properties:
        computeRole:
          $ref: '#/components/schemas/ComputeRole'
        isSystemExtension:
          description: Specifies if product is a Virtual Machine Extension.
          readOnly: true
          type: boolean
        sourceBlob:
          $ref: '#/components/schemas/Uri'
        supportMultipleExtensions:
          description: Indicates if specified product supports multiple extensions.
          readOnly: true
          type: boolean
        version:
          description: Specifies product version.
          readOnly: true
          type: string
        vmOsType:
          $ref: '#/components/schemas/OperatingSystem'
        vmScaleSetEnabled:
          description: Indicates if virtual machine Scale Set is enabled in the specified
            product.
          readOnly: true
          type: boolean
      type: object
    VirtualMachineProductProperties:
      description: Product information.
      properties:
        dataDiskImages:
          description: List of attached data disks.
          items:
            $ref: '#/components/schemas/DataDiskImage'
          readOnly: true
          type: array
        osDiskImage:
          $ref: '#/components/schemas/OsDiskImage'
        version:
          description: Specifies product version.
          readOnly: true
          type: string
      type: object
    Products_List_default_response_error:
      description: The details of the error.
      example:
        code: code
        message: message
        target: target
      properties:
        code:
          description: Error code.
          readOnly: true
          type: string
        message:
          description: Error message indicating why the operation failed.
          readOnly: true
          type: string
        target:
          description: The target of the particular error.
          readOnly: true
          type: string
      type: object
    Products_List_default_response:
      description: Error response indicates that the service is not able to process
        the incoming request. The reason is provided in the error message.
      example:
        error:
          code: code
          message: message
          target: target
      properties:
        error:
          $ref: '#/components/schemas/Products_List_default_response_error'
      type: object
  securitySchemes:
    azure_auth:
      description: Authorization uses an Azure Active Directory OAuth2 flow.
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
      type: oauth2
x-original-swagger-version: "2.0"

