openapi: 3.0.1
info:
  description: Client that can be used to manage Azure Search services and API keys.
  title: SearchManagementClient
  version: 2015-02-28
  x-apisguru-categories:
  - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
  - format: swagger
    url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/search/resource-manager/Microsoft.Search/stable/2015-02-28/search.json
    version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: search
  x-tags:
  - Azure
  - Microsoft
servers:
- url: https://management.azure.com/
security:
- azure_auth:
  - user_impersonation
paths:
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Search/searchServices:
    get:
      description: Returns a list of all Search services in the given resource group.
      externalDocs:
        url: https://msdn.microsoft.com/library/azure/dn832688.aspx
      operationId: services_list
      parameters:
      - description: The name of the resource group within the current subscription.
        in: path
        name: resourceGroupName
        required: true
        schema:
          type: string
      - description: Client Api Version.
        in: query
        name: api-version
        required: true
        schema:
          type: string
      - description: Gets subscription credentials which uniquely identify Microsoft
          Azure subscription. The subscription ID forms part of the URI for every
          service call.
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchServiceListResult'
            text/json:
              schema:
                $ref: '#/components/schemas/SearchServiceListResult'
          description: ""
      tags:
      - Services
      x-openapi-router-controller: openapi_server.controllers.services_controller
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Search/searchServices/{serviceName}:
    delete:
      description: "Deletes a Search service in the given resource group, along with\
        \ its associated resources."
      externalDocs:
        url: https://msdn.microsoft.com/library/azure/dn832692.aspx
      operationId: services_delete
      parameters:
      - description: The name of the resource group within the current subscription.
        in: path
        name: resourceGroupName
        required: true
        schema:
          type: string
      - description: The name of the Search service to delete.
        in: path
        name: serviceName
        required: true
        schema:
          type: string
      - description: Client Api Version.
        in: query
        name: api_version
        required: true
        schema:
          type: string
      - description: Gets subscription credentials which uniquely identify Microsoft
          Azure subscription. The subscription ID forms part of the URI for every
          service call.
        in: path
        name: subscription_id
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: ""
        "204":
          content: {}
          description: ""
        "404":
          content: {}
          description: ""
      tags:
      - Services
      x-openapi-router-controller: openapi_server.controllers.services_controller
    put:
      description: "Creates or updates a Search service in the given resource group.\
        \ If the Search service already exists, all properties will be updated with\
        \ the given values."
      externalDocs:
        url: https://msdn.microsoft.com/library/azure/dn832687.aspx
      operationId: services_create_or_update
      parameters:
      - description: The name of the resource group within the current subscription.
        in: path
        name: resourceGroupName
        required: true
        schema:
          type: string
      - description: The name of the Search service to create or update.
        in: path
        name: serviceName
        required: true
        schema:
          type: string
      - description: Client Api Version.
        in: query
        name: api_version
        required: true
        schema:
          type: string
      - description: Gets subscription credentials which uniquely identify Microsoft
          Azure subscription. The subscription ID forms part of the URI for every
          service call.
        in: path
        name: subscription_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchServiceCreateOrUpdateParameters'
          text/json:
            schema:
              $ref: '#/components/schemas/SearchServiceCreateOrUpdateParameters'
        description: The properties to set or update on the Search service.
        required: true
        x-body-name: parameters
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchServiceResource'
            text/json:
              schema:
                $ref: '#/components/schemas/SearchServiceResource'
          description: ""
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchServiceResource'
            text/json:
              schema:
                $ref: '#/components/schemas/SearchServiceResource'
          description: ""
      tags:
      - Services
      x-codegen-request-body-name: parameters
      x-openapi-router-controller: openapi_server.controllers.services_controller
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Search/searchServices/{serviceName}/listAdminKeys
  : post:
      description: Returns the primary and secondary API keys for the given Azure
        Search service.
      externalDocs:
        url: https://msdn.microsoft.com/library/azure/dn832685.aspx
      operationId: admin_keys_list
      parameters:
      - description: The name of the resource group within the current subscription.
        in: path
        name: resourceGroupName
        required: true
        schema:
          type: string
      - description: The name of the Search service for which to list admin keys.
        in: path
        name: serviceName
        required: true
        schema:
          type: string
      - description: Client Api Version.
        in: query
        name: api_version
        required: true
        schema:
          type: string
      - description: Gets subscription credentials which uniquely identify Microsoft
          Azure subscription. The subscription ID forms part of the URI for every
          service call.
        in: path
        name: subscription_id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminKeyResult'
            text/json:
              schema:
                $ref: '#/components/schemas/AdminKeyResult'
          description: ""
      tags:
      - AdminKeys
      x-openapi-router-controller: openapi_server.controllers.admin_keys_controller
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Search/searchServices/{serviceName}/listQueryKeys
  : get:
      description: Returns the list of query API keys for the given Azure Search service.
      externalDocs:
        url: https://msdn.microsoft.com/library/azure/dn832701.aspx
      operationId: query_keys_list
      parameters:
      - description: The name of the resource group within the current subscription.
        in: path
        name: resourceGroupName
        required: true
        schema:
          type: string
      - description: The name of the Search service for which to list query keys.
        in: path
        name: serviceName
        required: true
        schema:
          type: string
      - description: Client Api Version.
        in: query
        name: api_version
        required: true
        schema:
          type: string
      - description: Gets subscription credentials which uniquely identify Microsoft
          Azure subscription. The subscription ID forms part of the URI for every
          service call.
        in: path
        name: subscription_id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListQueryKeysResult'
            text/json:
              schema:
                $ref: '#/components/schemas/ListQueryKeysResult'
          description: ""
      tags:
      - QueryKeys
      x-openapi-router-controller: openapi_server.controllers.query_keys_controller
components:
  parameters:
    ApiVersionParameter:
      description: Client Api Version.
      in: query
      name: api-version
      required: true
      schema:
        type: string
    SubscriptionIdParameter:
      description: Gets subscription credentials which uniquely identify Microsoft
        Azure subscription. The subscription ID forms part of the URI for every service
        call.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
  schemas:
    AdminKeyResult:
      description: Response containing the primary and secondary API keys for a given
        Azure Search service.
      example:
        secondaryKey: secondaryKey
        primaryKey: primaryKey
      properties:
        primaryKey:
          description: The primary API key of the Search service.
          readOnly: true
          title: primaryKey
          type: string
        secondaryKey:
          description: The secondary API key of the Search service.
          readOnly: true
          title: secondaryKey
          type: string
      title: AdminKeyResult
      type: object
    ListQueryKeysResult:
      description: Response containing the query API keys for a given Azure Search
        service.
      example:
        value:
        - name: name
          key: key
        - name: name
          key: key
      properties:
        value:
          description: The query keys for the Azure Search service.
          items:
            $ref: '#/components/schemas/QueryKey'
          readOnly: true
          title: value
          type: array
      title: ListQueryKeysResult
      type: object
    QueryKey:
      description: Describes an API key for a given Azure Search service that has
        permissions for query operations only.
      example:
        name: name
        key: key
      properties:
        key:
          description: The value of the query API key.
          readOnly: true
          title: key
          type: string
        name:
          description: The name of the query API key; may be empty.
          readOnly: true
          title: name
          type: string
      title: QueryKey
      type: object
    Resource:
      properties:
        id:
          description: Resource Id
          readOnly: true
          type: string
        location:
          description: Resource location
          type: string
        name:
          description: Resource name
          readOnly: true
          type: string
        tags:
          additionalProperties:
            type: string
          description: Resource tags
          type: object
        type:
          description: Resource type
          readOnly: true
          type: string
      required:
      - location
      type: object
      x-ms-external: true
    SearchServiceCreateOrUpdateParameters:
      description: Properties that describe an Azure Search service.
      example:
        location: location
        properties:
          partitionCount: 0
          replicaCount: 6
          sku:
            name: free
        tags:
          key: tags
      properties:
        location:
          description: The geographic location of the Search service.
          title: location
          type: string
        properties:
          $ref: '#/components/schemas/SearchServiceProperties'
        tags:
          additionalProperties:
            type: string
          description: Tags to help categorize the Search service in the Azure Portal.
          title: tags
          type: object
      title: SearchServiceCreateOrUpdateParameters
      type: object
    SearchServiceListResult:
      description: Response containing a list of Azure Search services for a given
        resource group.
      example:
        value:
        - name: name
          location: location
          id: id
          properties:
            partitionCount: 0
            replicaCount: 6
            statusDetails: statusDetails
            provisioningState: succeeded
            sku:
              name: free
            status: running
          tags:
            key: tags
        - name: name
          location: location
          id: id
          properties:
            partitionCount: 0
            replicaCount: 6
            statusDetails: statusDetails
            provisioningState: succeeded
            sku:
              name: free
            status: running
          tags:
            key: tags
      properties:
        value:
          description: The Search services in the resource group.
          items:
            $ref: '#/components/schemas/SearchServiceResource'
          readOnly: true
          title: value
          type: array
      title: SearchServiceListResult
      type: object
    SearchServiceProperties:
      description: Defines properties of an Azure Search service that can be modified.
      example:
        partitionCount: 0
        replicaCount: 6
        sku:
          name: free
      properties:
        partitionCount:
          description: "The number of partitions in the Search service; if specified,\
            \ it can be 1, 2, 3, 4, 6, or 12."
          format: int32
          title: partitionCount
          type: integer
        replicaCount:
          description: "The number of replicas in the Search service. If specified,\
            \ it must be a value between 1 and 6 inclusive."
          format: int32
          title: replicaCount
          type: integer
        sku:
          $ref: '#/components/schemas/Sku'
      title: SearchServiceProperties
      type: object
    SearchServiceReadableProperties:
      description: Defines all the properties of an Azure Search service.
      example:
        partitionCount: 0
        replicaCount: 6
        statusDetails: statusDetails
        provisioningState: succeeded
        sku:
          name: free
        status: running
      properties:
        partitionCount:
          description: "The number of partitions in the Search service; if specified,\
            \ it can be 1, 2, 3, 4, 6, or 12."
          format: int32
          title: partitionCount
          type: integer
        provisioningState:
          description: The state of the last provisioning operation performed on the
            Search service.
          enum:
          - succeeded
          - provisioning
          - failed
          readOnly: true
          title: provisioningState
          type: string
          x-ms-enum:
            name: ProvisioningState
        replicaCount:
          description: "The number of replicas in the Search service. If specified,\
            \ it must be a value between 1 and 6 inclusive."
          format: int32
          title: replicaCount
          type: integer
        sku:
          $ref: '#/components/schemas/Sku'
        status:
          description: The status of the Search service.
          enum:
          - running
          - provisioning
          - deleting
          - degraded
          - disabled
          - error
          readOnly: true
          title: status
          type: string
          x-ms-enum:
            name: SearchServiceStatus
        statusDetails:
          description: The details of the Search service status.
          readOnly: true
          title: statusDetails
          type: string
      title: SearchServiceReadableProperties
      type: object
    SearchServiceResource:
      description: Describes an Azure Search service and its current state.
      example:
        name: name
        location: location
        id: id
        properties:
          partitionCount: 0
          replicaCount: 6
          statusDetails: statusDetails
          provisioningState: succeeded
          sku:
            name: free
          status: running
        tags:
          key: tags
      properties:
        id:
          description: The resource Id of the Azure Search service.
          readOnly: true
          title: id
          type: string
        location:
          description: The geographic location of the Search service.
          title: location
          type: string
        name:
          description: The name of the Search service.
          title: name
          type: string
        properties:
          $ref: '#/components/schemas/SearchServiceReadableProperties'
        tags:
          additionalProperties:
            type: string
          description: Tags to help categorize the Search service in the Azure Portal.
          title: tags
          type: object
      title: SearchServiceResource
      type: object
    Sku:
      description: "Defines the SKU of an Azure Search Service, which determines price\
        \ tier and capacity limits."
      example:
        name: free
      properties:
        name:
          description: The SKU of the Search service.
          enum:
          - free
          - standard
          - standard2
          title: name
          type: string
          x-ms-enum:
            name: SkuType
      title: Sku
      type: object
    SubResource:
      properties:
        id:
          description: Resource Id
          type: string
      type: object
      x-ms-external: true
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_azure_auth
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_azure_auth
x-original-swagger-version: "2.0"
