openapi: 3.0.1
info:
  description: Region health operation endpoints and objects.
  title: InfrastructureInsightsManagementClient
  version: 2016-05-01
  x-apisguru-categories:
  - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
  - format: swagger
    url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azsadmin/resource-manager/infrastructureinsights/Microsoft.InfrastructureInsights.Admin/preview/2016-05-01/RegionHealth.json
    version: "2.0"
  x-providerName: azure.com
  x-serviceName: azsadmin-RegionHealth
  x-tags:
  - Azure
  - Microsoft
servers:
- url: https://adminmanagement.local.azurestack.external/
security:
- azure_auth:
  - user_impersonation
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.InfrastructureInsights.Admin/regionHealths
  : get:
      description: Returns the list of all health status for the region.
      operationId: region_healths_list
      parameters:
      - description: Subscription credentials that uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
      - description: The name of the resource group.
        in: path
        name: resourceGroupName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Client API Version.
        in: query
        name: api-version
        required: true
        schema:
          default: 2016-05-01
          type: string
      - description: OData filter parameter.
        in: query
        name: $filter
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionHealthList'
          description: OK
      tags:
      - RegionHealths
      x-ms-examples:
        Returns the list of all health status for the region.:
          parameters:
            api-version: 2016-05-01
            resourceGroupName: System.local
            subscriptionId: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
          responses:
            "200":
              body:
                value:
                - id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/System.local/providers/Microsoft.InfrastructureInsights.Admin/regionHealths/local
                  location: local
                  name: local
                  properties:
                    alertSummary:
                      criticalAlertCount: 0
                      warningAlertCount: 2
                    usageMetrics:
                    - metricsValue:
                      - name: Used
                        unit: GB
                        value: 76.24941635131836
                      - name: Available
                        unit: GB
                        value: 181.7333984375
                      name: Physical memory
                    - metricsValue:
                      - name: Used
                        unit: TB
                        value: 0.22170669212937355
                      - name: Available
                        unit: TB
                        value: 2.2449070774018764
                      name: Physical storage
                    - metricsValue:
                      - name: Used
                        unit: One
                        value: 31
                      - name: Available
                        unit: One
                        value: 480
                      name: Public IP address pools
                  tags: {}
                  type: Microsoft.InfrastructureInsights.Admin/regionHealths
      x-ms-odata: '#/definitions/Alert'
      x-ms-pageable:
        nextLinkName: nextLink
      x-openapi-router-controller: openapi_server.controllers.region_healths_controller
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.InfrastructureInsights.Admin/regionHealths/{location}
  : get:
      description: Returns the requested health status of a region.
      operationId: region_healths_get
      parameters:
      - description: Subscription credentials that uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
      - description: The name of the resource group.
        in: path
        name: resourceGroupName
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Name of the region
        in: path
        name: location
        required: true
        schema:
          type: string
          x-ms-parameter-location: method
        x-ms-parameter-location: method
      - description: Client API Version.
        in: query
        name: api-version
        required: true
        schema:
          default: 2016-05-01
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionHealth'
          description: OK
      tags:
      - RegionHealths
      x-ms-examples:
        Returns the requested health status of a region.:
          parameters:
            api-version: 2016-05-01
            location: local
            resourceGroupName: System.local
            subscriptionId: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
          responses:
            "200":
              body:
                id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/System.local/providers/Microsoft.InfrastructureInsights.Admin/regionHealths/local
                location: local
                name: local
                properties:
                  alertSummary:
                    criticalAlertCount: 0
                    warningAlertCount: 2
                  usageMetrics:
                  - metricsValue:
                    - name: Used
                      unit: GB
                      value: 76.24941635131836
                    - name: Available
                      unit: GB
                      value: 181.7333984375
                    name: Physical memory
                  - metricsValue:
                    - name: Used
                      unit: TB
                      value: 0.22170669212937355
                    - name: Available
                      unit: TB
                      value: 2.2449070774018764
                    name: Physical storage
                  - metricsValue:
                    - name: Used
                      unit: One
                      value: 31
                    - name: Available
                      unit: One
                      value: 480
                    name: Public IP address pools
                tags: {}
                type: Microsoft.InfrastructureInsights.Admin/regionHealths
      x-openapi-router-controller: openapi_server.controllers.region_healths_controller
components:
  schemas:
    RegionHealth:
      allOf:
      - allOf:
        - description: The core properties of ARM resources
          properties:
            id:
              description: Fully qualified resource Id for the resource
              readOnly: true
              type: string
            name:
              description: The name of the resource
              readOnly: true
              type: string
            type:
              description: The type of the resource.
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
        description: The resource model definition for a ARM tracked top level resource
        properties:
          location:
            description: The Azure Region where the resource lives
            type: string
            x-ms-mutability:
            - read
            - create
          tags:
            additionalProperties:
              type: string
            description: Resource tags.
            type: object
            x-ms-mutability:
            - read
            - create
            - update
      description: Contains information related to the health of a region.
      example:
        properties:
          usageMetrics:
          - metricsValue:
            - unit: One
              sourceType: sourceType
              maCounterName: maCounterName
              name: name
              sourceName: PhysicalNode
              value: 1.4658129805029452
              observedTimestamp: 2000-01-23T04:56:07.000+00:00
            - unit: One
              sourceType: sourceType
              maCounterName: maCounterName
              name: name
              sourceName: PhysicalNode
              value: 1.4658129805029452
              observedTimestamp: 2000-01-23T04:56:07.000+00:00
            name: name
          - metricsValue:
            - unit: One
              sourceType: sourceType
              maCounterName: maCounterName
              name: name
              sourceName: PhysicalNode
              value: 1.4658129805029452
              observedTimestamp: 2000-01-23T04:56:07.000+00:00
            - unit: One
              sourceType: sourceType
              maCounterName: maCounterName
              name: name
              sourceName: PhysicalNode
              value: 1.4658129805029452
              observedTimestamp: 2000-01-23T04:56:07.000+00:00
            name: name
          alertSummary:
            warningAlertCount: 6
            criticalAlertCount: 0
      properties:
        properties:
          $ref: '#/components/schemas/RegionHealthModel'
      title: RegionHealth
    RegionHealthList:
      description: Pageable list of region health items.
      example:
        value:
        - properties:
            usageMetrics:
            - metricsValue:
              - unit: One
                sourceType: sourceType
                maCounterName: maCounterName
                name: name
                sourceName: PhysicalNode
                value: 1.4658129805029452
                observedTimestamp: 2000-01-23T04:56:07.000+00:00
              - unit: One
                sourceType: sourceType
                maCounterName: maCounterName
                name: name
                sourceName: PhysicalNode
                value: 1.4658129805029452
                observedTimestamp: 2000-01-23T04:56:07.000+00:00
              name: name
            - metricsValue:
              - unit: One
                sourceType: sourceType
                maCounterName: maCounterName
                name: name
                sourceName: PhysicalNode
                value: 1.4658129805029452
                observedTimestamp: 2000-01-23T04:56:07.000+00:00
              - unit: One
                sourceType: sourceType
                maCounterName: maCounterName
                name: name
                sourceName: PhysicalNode
                value: 1.4658129805029452
                observedTimestamp: 2000-01-23T04:56:07.000+00:00
              name: name
            alertSummary:
              warningAlertCount: 6
              criticalAlertCount: 0
        - properties:
            usageMetrics:
            - metricsValue:
              - unit: One
                sourceType: sourceType
                maCounterName: maCounterName
                name: name
                sourceName: PhysicalNode
                value: 1.4658129805029452
                observedTimestamp: 2000-01-23T04:56:07.000+00:00
              - unit: One
                sourceType: sourceType
                maCounterName: maCounterName
                name: name
                sourceName: PhysicalNode
                value: 1.4658129805029452
                observedTimestamp: 2000-01-23T04:56:07.000+00:00
              name: name
            - metricsValue:
              - unit: One
                sourceType: sourceType
                maCounterName: maCounterName
                name: name
                sourceName: PhysicalNode
                value: 1.4658129805029452
                observedTimestamp: 2000-01-23T04:56:07.000+00:00
              - unit: One
                sourceType: sourceType
                maCounterName: maCounterName
                name: name
                sourceName: PhysicalNode
                value: 1.4658129805029452
                observedTimestamp: 2000-01-23T04:56:07.000+00:00
              name: name
            alertSummary:
              warningAlertCount: 6
              criticalAlertCount: 0
        nextLink: nextLink
      properties:
        nextLink:
          description: URI to next page.
          title: nextLink
          type: string
        value:
          description: Array of region health items
          items:
            $ref: '#/components/schemas/RegionHealth'
          title: value
          type: array
      title: RegionHealthList
      type: object
    RegionHealthModel:
      description: Contains information related to the health of a region.
      example:
        usageMetrics:
        - metricsValue:
          - unit: One
            sourceType: sourceType
            maCounterName: maCounterName
            name: name
            sourceName: PhysicalNode
            value: 1.4658129805029452
            observedTimestamp: 2000-01-23T04:56:07.000+00:00
          - unit: One
            sourceType: sourceType
            maCounterName: maCounterName
            name: name
            sourceName: PhysicalNode
            value: 1.4658129805029452
            observedTimestamp: 2000-01-23T04:56:07.000+00:00
          name: name
        - metricsValue:
          - unit: One
            sourceType: sourceType
            maCounterName: maCounterName
            name: name
            sourceName: PhysicalNode
            value: 1.4658129805029452
            observedTimestamp: 2000-01-23T04:56:07.000+00:00
          - unit: One
            sourceType: sourceType
            maCounterName: maCounterName
            name: name
            sourceName: PhysicalNode
            value: 1.4658129805029452
            observedTimestamp: 2000-01-23T04:56:07.000+00:00
          name: name
        alertSummary:
          warningAlertCount: 6
          criticalAlertCount: 0
      properties:
        alertSummary:
          $ref: '#/components/schemas/RegionHealthModel_alertSummary'
        usageMetrics:
          description: List of usage metrics for the region.
          items:
            $ref: '#/components/schemas/RegionHealthModel_usageMetrics_inner'
          title: usageMetrics
          type: array
      title: RegionHealthModel
      type: object
    RegionHealthModel_alertSummary:
      description: Summary of the alerts.
      example:
        warningAlertCount: 6
        criticalAlertCount: 0
      properties:
        criticalAlertCount:
          description: The number of critical alerts for the service.
          title: criticalAlertCount
          type: integer
        warningAlertCount:
          description: The number of warning alerts for the service.
          title: warningAlertCount
          type: integer
      title: RegionHealthModel_alertSummary
      type: object
    RegionHealthModel_usageMetrics_inner_metricsValue_inner:
      description: Metrics for a source.
      example:
        unit: One
        sourceType: sourceType
        maCounterName: maCounterName
        name: name
        sourceName: PhysicalNode
        value: 1.4658129805029452
        observedTimestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        maCounterName:
          description: Name of the counter.
          title: maCounterName
          type: string
        name:
          description: Name of the usage metric.
          title: name
          type: string
        observedTimestamp:
          description: Time counter was observed.
          format: date-time
          title: observedTimestamp
          type: string
        sourceName:
          description: The origin of the metric.
          enum:
          - PhysicalNode
          - VirtualMachine
          - ResourceProvider
          title: sourceName
          type: string
          x-ms-enum:
            modelAsString: true
            name: MetricsSourceType
        sourceType:
          description: Type of the source.
          title: sourceType
          type: string
        unit:
          description: The unit of the metric.
          enum:
          - One
          - Percentage
          - B
          - KB
          - MB
          - GB
          - TB
          title: unit
          type: string
          x-ms-enum:
            modelAsString: true
            name: MetricsUnit
        value:
          description: Name of the usage metric.
          format: double
          title: value
          type: number
      title: RegionHealthModel_usageMetrics_inner_metricsValue_inner
      type: object
    RegionHealthModel_usageMetrics_inner:
      description: Metrics of resource usage.
      example:
        metricsValue:
        - unit: One
          sourceType: sourceType
          maCounterName: maCounterName
          name: name
          sourceName: PhysicalNode
          value: 1.4658129805029452
          observedTimestamp: 2000-01-23T04:56:07.000+00:00
        - unit: One
          sourceType: sourceType
          maCounterName: maCounterName
          name: name
          sourceName: PhysicalNode
          value: 1.4658129805029452
          observedTimestamp: 2000-01-23T04:56:07.000+00:00
        name: name
      properties:
        metricsValue:
          description: List of usage metrics.
          items:
            $ref: '#/components/schemas/RegionHealthModel_usageMetrics_inner_metricsValue_inner'
          title: metricsValue
          type: array
        name:
          description: Name of the usage metric.
          title: name
          type: string
      title: RegionHealthModel_usageMetrics_inner
      type: object
  securitySchemes:
    azure_auth:
      description: Authorization uses an Azure Active Directory OAuth2 flow.
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_azure_auth
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_azure_auth
x-original-swagger-version: "2.0"
